#### Initialize the libraries, the environment and the client

In [1]:
import pandas as pd
import os

try:
    from epo.tipdata.ops import OPSClient, models, exceptions
except ImportError:
    os.system('pip install epo-tipdata-ops')
    from epo.tipdata.ops import OPSClient, models, exceptions

%load_ext dotenv
%dotenv
%load_ext autoreload
%autoreload 2
    
client = OPSClient(
    key=os.getenv("OPS_KEY"), secret=os.getenv("OPS_SECRET")
)

### 7.4 Number Request Method
#### 7.4.1 number(reference_type, input, output_format, output_type)
* Converts a patent number from one format to another (e.g., publication number to application number).<br>
* Parameters:<br>  
```reference_type (str)```: Type of patent reference (e.g., "publication", "application", or "priority")<br>
```input (Original, Epodoc, Docdb)```: Patent document identifier in any format<br>
```output_format (str)```: Desired format for the output patent number<br>
```output_type (str)```: Format of the returned data (raw XML or Pandas DataFrame)<br>

#### 7.4.2 Example of making a number request
This example demonstrates converting a patent application number from its original format to the Epodoc format once delivering a XML output read with print() and once into a dataframe.

In [28]:
from pprint import pprint 

epodoc_xml = client.number(
    reference_type="priority",
    input=models.Original("62/570,391", "US", "A", "20171010"),
    output_format="epodoc",
    output_type="raw"
)
# Print the converted Epodoc number
pprint(f"Converted document number: {epodoc_xml}")

# Reset to default options if needed with pd.reset_option('display.max_colwidth')
pd.set_option('display.max_colwidth', 20000)

epodoc = client.number(
    reference_type="priority",
    input=models.Original("62/570,391", "US", "A", "20171010"),
    output_format="epodoc",
    output_type="dataframe"
)
# Print the converted Epodoc number
print(f"Converted document number: {epodoc}")
display(epodoc)

('Converted document number: <?xml version="1.0" encoding="UTF-8"?>\n'
 '<ops:world-patent-data xmlns="http://www.epo.org/exchange" '
 'xmlns:ops="http://ops.epo.org" xmlns:xlink="http://www.w3.org/1999/xlink">\n'
 '    <ops:meta name="status" value="pBRE015"/>\n'
 '    <ops:standardization inputFormat="original" outputFormat="epodoc">\n'
 '        <ops:input>\n'
 '            <ops:priority-claim>\n'
 '                <document-id document-id-type="original">\n'
 '                    <country>US</country>\n'
 '                    <doc-number>62/570,391</doc-number>\n'
 '                    <kind>A</kind>\n'
 '                    <date>20171010</date>\n'
 '                </document-id>\n'
 '            </ops:priority-claim>\n'
 '        </ops:input>\n'
 '        <ops:output>\n'
 '            <ops:priority-claim>\n'
 '                <document-id document-id-type="epodoc">\n'
 '                    <doc-number>US201762570391P</doc-number>\n'
 '                    <kind>P</kind>\n'
 '                    <date>20171010</date>\n'
 '                </document-id>\n'
 '            </ops:priority-claim>\n'
 '        </ops:output>\n'
 '    </ops:standardization>\n'
 '</ops:world-patent-data>')
Converted document number:   inputFormat outputFormat  \
0    original       epodoc

                                                                          ops:input|ops:priority-claim|document-id  \
0  {'@document-id-type': 'original', 'country': 'US', 'doc-number': '62/570,391', 'kind': 'A', 'date': '20171010'}

                                                           ops:output|ops:priority-claim|document-id
0  {'@document-id-type': 'epodoc', 'doc-number': 'US201762570391P', 'kind': 'P', 'date': '20171010'}

,inputFormat,outputFormat,ops:input|ops:priority-claim|document-id,ops:output|ops:priority-claim|document-id
0,original,epodoc,"{'@document-id-type': 'original', 'country': 'US', 'doc-number': '62/570,391', 'kind': 'A', 'date': '20171010'}","{'@document-id-type': 'epodoc', 'doc-number': 'US201762570391P', 'kind': 'P', 'date': '20171010'}"

In [32]:
from pprint import pprint 

original_xml = client.number(
    reference_type="application",
    input=models.Docdb("201762570391", "US", "P"),
    output_format="original",
    output_type="raw"
)
# Print the converted Epodoc number
pprint(f"Converted document number: {original_xml}")

# Reset to default options if needed with pd.reset_option('display.max_colwidth')
pd.set_option('display.max_colwidth', 20000)

original = client.number(
    reference_type="application",
    input=models.Docdb("201762570391", "US", "P"),
    output_format="original",
    output_type="dataframe"
)
# Print the converted Epodoc number
print(f"Converted document number: {original}")
display(original)

('Converted document number: <?xml version="1.0" encoding="UTF-8"?>\n'
 '<ops:world-patent-data xmlns="http://www.epo.org/exchange" '
 'xmlns:ops="http://ops.epo.org" xmlns:xlink="http://www.w3.org/1999/xlink">\n'
 '    <ops:meta name="status" value="pBRE015 pBRE027"/>\n'
 '    <ops:standardization inputFormat="docdb" outputFormat="original">\n'
 '        <ops:input>\n'
 '            <ops:application-reference>\n'
 '                <document-id document-id-type="docdb">\n'
 '                    <country>US</country>\n'
 '                    <doc-number>201762570391</doc-number>\n'
 '                    <kind>P</kind>\n'
 '                </document-id>\n'
 '            </ops:application-reference>\n'
 '        </ops:input>\n'
 '        <ops:output>\n'
 '            <ops:application-reference>\n'
 '                <document-id document-id-type="original">\n'
 '                    <country>US</country>\n'
 '                    <doc-number>62570391</doc-number>\n'
 '                </document-id>\n'
 '            </ops:application-reference>\n'
 '        </ops:output>\n'
 '    </ops:standardization>\n'
 '</ops:world-patent-data>')
Converted document number:   inputFormat outputFormat  \
0       docdb     original

                                              ops:input|ops:application-reference|document-id  \
0  {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '201762570391', 'kind': 'P'}

                               ops:output|ops:application-reference|document-id
0  {'@document-id-type': 'original', 'country': 'US', 'doc-number': '62570391'}

,inputFormat,outputFormat,ops:input|ops:application-reference|document-id,ops:output|ops:application-reference|document-id
0,docdb,original,"{'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '201762570391', 'kind': 'P'}","{'@document-id-type': 'original', 'country': 'US', 'doc-number': '62570391'}"

In [35]:
import pandas as pd
from pprint import pprint

# Reset to default options if needed
pd.set_option('display.max_colwidth', 20000)

# Fetch the response in DataFrame format
original = client.number(
    reference_type="application",
    input=models.Docdb("201762570391", "US", "P"),
    output_format="original",
    output_type="dataframe"
)

# Function to format the document ID fields
def format_document_id(doc_id):
    """Extracts and formats relevant fields from document-id dictionaries."""
    if isinstance(doc_id, dict):
        country = doc_id.get("country", "")
        doc_number = doc_id.get("doc-number", "")
        kind = doc_id.get("kind", "")
        return f"{country}{doc_number}{kind}".strip()
    return doc_id  # Return as is if not a dictionary

# Apply formatting to relevant columns
for col in original.columns:
    if "document-id" in col:
        original[col] = original[col].apply(format_document_id)

# Print and display the formatted DataFrame
print(f"Converted document number:\n{original}")
display(original)

Converted document number:
  inputFormat outputFormat ops:input|ops:application-reference|document-id  \
0       docdb     original                                 US201762570391P

  ops:output|ops:application-reference|document-id
0                                       US62570391

,inputFormat,outputFormat,ops:input|ops:application-reference|document-id,ops:output|ops:application-reference|document-id
0,docdb,original,US201762570391P,US62570391

In [44]:
import pandas as pd
from pprint import pprint

# Reset to default options if needed
pd.set_option('display.max_colwidth', 20000)

# Fetch the response in DataFrame format for epodoc conversion
epodoc = client.number(
    reference_type="priority",  # Ensure we're handling a priority reference
    input=models.Original("62/570,391", "US", "A", "20171010"),
    output_format="epodoc",
    output_type="dataframe"
)

# Check the column names in the epodoc DataFrame
print("Epodoc DataFrame Columns:", epodoc.columns)

# Apply the same formatting function to relevant document ID columns
def format_document_id(doc_id):
    """Extracts and formats relevant fields from document-id dictionaries."""
    if isinstance(doc_id, dict):
        country = doc_id.get("country", "")
        doc_number = doc_id.get("doc-number", "")
        
        return f"{country}{doc_number}".strip()
    return doc_id  # Return as is if not a dictionary

# Apply formatting to relevant columns
for col in epodoc.columns:
    if "document-id" in col:
        epodoc[col] = epodoc[col].apply(format_document_id)

# Verify available columns and determine correct input/output keys
matching_columns = [col for col in epodoc.columns if "document-id" in col]
print("Matching Columns for Document IDs:", matching_columns)

# Identify correct column names based on the available DataFrame structure
input_col = next((col for col in matching_columns if "ops:input" in col), None)
output_col = next((col for col in matching_columns if "ops:output" in col), None)

if input_col and output_col:
    # Extract document information if the columns exist
    input_doc_info = epodoc[input_col].iloc[0]
    output_doc_info = epodoc[output_col].iloc[0]

    # Extract specific values such as 'doc-number' and 'country'
    input_doc_number = input_doc_info.split()[0] if isinstance(input_doc_info, str) else 'N/A'
    output_doc_number = output_doc_info.split()[0] if isinstance(output_doc_info, str) else 'N/A'
    output_country = output_doc_number[:2] if output_doc_number else 'N/A'

    # Print the converted Epodoc number
    print(f"Input Document: {input_doc_number}")
    print(f"Converted Epodoc Priority: {output_doc_number}")
else:
    print("Warning: Could not find expected document ID columns!")

# Display the final formatted Epodoc DataFrame
print("Formatted Epodoc DataFrame:")
display(epodoc)

Epodoc DataFrame Columns: Index(['inputFormat', 'outputFormat',
       'ops:input|ops:priority-claim|document-id',
       'ops:output|ops:priority-claim|document-id'],
      dtype='object')
Matching Columns for Document IDs: ['ops:input|ops:priority-claim|document-id', 'ops:output|ops:priority-claim|document-id']
Input Document: US62/570,391
Converted Epodoc Priority: US201762570391P
Formatted Epodoc DataFrame:

,inputFormat,outputFormat,ops:input|ops:priority-claim|document-id,ops:output|ops:priority-claim|document-id
0,original,epodoc,"US62/570,391",US201762570391P

#### Explanation:
1. We define the original patent application number in its original format, including the date (important for accurate conversion).<br>
2. We create an Original object with the original number and date.<br>
3. We specify the desired output format as Epodoc.<br>
4. We call the number method with the following arguments:<br>  
```reference_type```: Set to "application" as we're converting an application number.<br>
```input```: The my_original object containing the original number and date.<br>
```output_format```: Set to epodoc to get the converted number in Epodoc format.<br>
```output_type```: Set once to "raw" (default) to get the converted number as a XML string and once to "dataframe" to get the converted number along with additional information in a Pandas dataframe.<br><br>
The number method will then convert the original number to the Epodoc format based on the provided date. Finally, it uses _get_content to return the converted number as a string.<br>

#### Note:
* This example assumes a specific format for the original patent application number. You might need to adjust it based on the actual format of your original number.<br>