#### Initialize the libraries, the environment and the client

In [1]:
import pandas as pd
import os

try:
    from epo.tipdata.ops import OPSClient, models, exceptions
except ImportError:
    os.system('pip install epo-tipdata-ops')
    from epo.tipdata.ops import OPSClient, models, exceptions

%load_ext dotenv
%dotenv
%load_ext autoreload
%autoreload 2
    
client = OPSClient(
    key=os.getenv("OPS_KEY"), secret=os.getenv("OPS_SECRET")
)

### 7.2 Family Method
#### 7.2.1	family(reference_type, input, constituents, output_type)

* Retrieves the extended patent family information for a given patent, providing details of related patents across different jurisdictions.
* Parameters:

```reference_type (str)```: Type of patent reference (e.g., "publication", "application", or "priority")<br>
```input (Epodoc or Docdb)```: Patent document identifier<br>
```constituents (list[str], optional)```: Additional information to retrieve (bibliographic or legal data)<br>
```output_type (str)```: Format of the returned data (raw XML or Pandas DataFrame)<br>

#### 7.2.2	Example of fetching from Docdb a family by publication
This example retrieves the INPADOC family information (patent numbers of related applications) for a published Japanese patent identified by its document number stored in the Docdb object.

In [2]:
family_xml = client.family(
    reference_type="publication",    
    input=models.Docdb("4106326", "EP", "A1"), # input=models.Docdb("2101496", "EP", "B1"),  # input=models.Docdb("2995292", "JP", "B1"),
    constituents=["biblio"],
    output_type="raw",
)
print(family_xml[:2000])

family_df = client.family(
    reference_type="publication",    
    input=models.Docdb("4106326", "EP", "A1"), # input=models.Docdb("2101496", "EP", "B1"),  # input=models.Docdb("2995292", "JP", "B1"),
    constituents=None,
    output_type="dataframe",
)
family_df

<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="../../../../../style/family-biblio.xsl"?>
<ops:world-patent-data xmlns="http://www.epo.org/exchange" xmlns:ops="http://ops.epo.org" xmlns:xlink="http://www.w3.org/1999/xlink">
    <ops:patent-family legal="false" total-result-count="2">
        <ops:publication-reference>
            <document-id document-id-type="docdb">
                <country>EP</country>
                <doc-number>4106326</doc-number>
                <kind>A1</kind>
            </document-id>
        </ops:publication-reference>
        <ops:family-member family-id="82067485">
            <publication-reference>
                <document-id document-id-type="docdb">
                    <country>EP</country>
                    <doc-number>4106326</doc-number>
                    <kind>A1</kind>
                    <date>20221221</date>
                </document-id>
                <document-id document-id-type="epodoc">
                    <doc-number>EP4106326</doc-number>
                    <date>20221221</date>
                </document-id>
            </publication-reference>
            <application-reference doc-id="574299984" is-representative="YES">
                <document-id document-id-type="docdb">
                    <country>EP</country>
                    <doc-number>22179301</doc-number>
                    <kind>A</kind>
                    <date>20220615</date>
                </document-id>
            </application-reference>
            <priority-claim sequence="1" kind="national">
                <document-id document-id-type="docdb">
                    <country>US</country>
                    <doc-number>202217806216</doc-number>
                    <kind>A</kind>
                    <date>20220609</date>
                </document-id>
                <priority-active-indicator>YES</priority-active-indicator>
            </priority-claim>
            <priority-claim sequence="2" kind="nat

,legal,total-result-count,ops:family-member|family-id,ops:family-member|publication-reference,ops:family-member|application-reference,ops:family-member|priority-claim,ops:publication-reference|document-id|document-id-type,ops:publication-reference|document-id|country,ops:publication-reference|document-id|doc-number,ops:publication-reference|document-id|kind
0,false,2,82067485,{'document-id': [{'@document-id-type': 'docdb'...,"{'@doc-id': '574299984', '@is-representative':...","[{'@sequence': '1', '@kind': 'national', 'docu...",docdb,EP,4106326,A1
1,false,2,82067485,{'document-id': [{'@document-id-type': 'docdb'...,"{'@doc-id': '584535325', 'document-id': {'@doc...","[{'@sequence': '1', '@kind': 'national', 'docu...",docdb,EP,4106326,A1

#### 7.2.2.1 The variable family_xml will be used for programmatic purposes to:
* Parse the XML response
* Define namespaces correctly

In [3]:
import xml.etree.ElementTree as ET
from pprint import pprint

# Parse the XML data
root = ET.fromstring(family_xml)
pprint(family_xml[:1000])

# Define namespaces
namespaces = {
    'ops': 'http://ops.epo.org',
    '': 'http://www.epo.org/exchange',
    'xlink': 'http://www.w3.org/1999/xlink'
}

('<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" '
 'href="../../../../../style/family-biblio.xsl"?>\n'
 '<ops:world-patent-data xmlns="http://www.epo.org/exchange" '
 'xmlns:ops="http://ops.epo.org" xmlns:xlink="http://www.w3.org/1999/xlink">\n'
 '    <ops:patent-family legal="false" total-result-count="2">\n'
 '        <ops:publication-reference>\n'
 '            <document-id document-id-type="docdb">\n'
 '                <country>EP</country>\n'
 '                <doc-number>4106326</doc-number>\n'
 '                <kind>A1</kind>\n'
 '            </document-id>\n'
 '        </ops:publication-reference>\n'
 '        <ops:family-member family-id="82067485">\n'
 '            <publication-reference>\n'
 '                <document-id document-id-type="docdb">\n'
 '                    <country>EP</country>\n'
 '                    <doc-number>4106326</doc-number>\n'
 '                    <kind>A1</kind>\n'
 '                    <date>20221221</date>\n'
 '                </document-id>\n'
 '                <document-id document-id-type="epodoc">\n'
 '                ')

This code works similarly to the prior example for published_data. Here is what it does:

* We import the Docdb class to represent the patent document.
* We define the document number for the published patent.
* We create an Docdb object with that number.
* The family method is called with the following arguments:
```reference_type```: Set to "publication" as we're looking for a published patent.
```input```: The input object containing the document number.
```constituents```: Set to None by default, retrieving all family information. (Optional: Set to a list containing "biblio" and/or "legal" for specific data).
```output_type```: Set to "dataframe" (optional) to get the data as a Pandas DataFrame for easier manipulation.

The family method retrieves the INPADOC family information for the input patent. It then uses the _get_content method to convert the response to the desired format (DataFrame in this case, or raw XML if not specified). The last line checks the type of the returned data. If it's a DataFrame, it prints the first few rows containing information about the family members (patent numbers etc.). If it's raw XML, it informs the user that additional parsing might be needed to access the data. In this case the command pprint(family) facilitates reading of XML data.

#### 7.2.2.2 We extract the document details:
* the document number
* the country code
* the kind code

In [4]:
# Initialize the set to keep track of unique document numbers
unique_documents = set()
# Extract all document numbers
document_details = []

# Find all 'document-id' elements
for doc_id in root.findall(".//{http://www.epo.org/exchange}document-id"):
    # Debug print to show the document_id element
    # print(f"Found document-id element: {ET.tostring(doc_id, encoding='unicode')}")    
    doc_number = doc_id.find('{http://www.epo.org/exchange}doc-number')
    country = doc_id.find("{http://www.epo.org/exchange}country")
    kind = doc_id.find("{http://www.epo.org/exchange}kind")    
    if doc_number is not None and doc_number.text not in unique_documents and country is not None and kind is not None:
        # Add the document number to the set
        unique_documents.add(doc_number.text)
        document_details.append({
            'doc_number': doc_number.text,
            'country': country.text,
            'kind': kind.text
        })
        
# Print the extracted document numbers
print("document details:", document_details[:50])

document details: [{'doc_number': '4106326', 'country': 'EP', 'kind': 'A1'}, {'doc_number': '22179301', 'country': 'EP', 'kind': 'A'}, {'doc_number': '202217806216', 'country': 'US', 'kind': 'A'}, {'doc_number': '202163202527', 'country': 'US', 'kind': 'P'}, {'doc_number': '202762632025', 'country': 'US', 'kind': None}, {'doc_number': '8395653', 'country': 'US', 'kind': 'B2'}, {'doc_number': '8842161', 'country': 'US', 'kind': 'B2'}, {'doc_number': '9030520', 'country': 'US', 'kind': 'B2'}, {'doc_number': '9542603', 'country': 'US', 'kind': 'B2'}, {'doc_number': '9723260', 'country': 'US', 'kind': 'B2'}, {'doc_number': '9800835', 'country': 'US', 'kind': 'B2'}, {'doc_number': '10091412', 'country': 'US', 'kind': 'B1'}, {'doc_number': '10122972', 'country': 'US', 'kind': 'B2'}, {'doc_number': '10187579', 'country': 'US', 'kind': 'B1'}, {'doc_number': '10574899', 'country': 'US', 'kind': 'B2'}, {'doc_number': '2020103078', 'country': 'WO', 'kind': 'A1'}, {'doc_number': '2020103068', 'country': 'WO', 'kind': 'A1'}, {'doc_number': '10778941', 'country': 'US', 'kind': 'B1'}, {'doc_number': '2011285807', 'country': 'US', 'kind': 'A1'}, {'doc_number': '2012320143', 'country': 'US', 'kind': 'A1'}, {'doc_number': '9930270', 'country': 'US', 'kind': 'B2'}, {'doc_number': '2020351435', 'country': 'US', 'kind': 'A1'}, {'doc_number': '10904485', 'country': 'US', 'kind': 'B1'}, {'doc_number': '2022400244', 'country': 'US', 'kind': 'A1'}, {'doc_number': '2010149369', 'country': 'US', 'kind': 'A1'}, {'doc_number': '2010238262', 'country': 'US', 'kind': 'A1'}, {'doc_number': '2012327179', 'country': 'US', 'kind': 'A1'}, {'doc_number': '2016309157', 'country': 'US', 'kind': 'A1'}, {'doc_number': '2017264864', 'country': 'US', 'kind': 'A1'}, {'doc_number': '2021306555', 'country': 'US', 'kind': 'A1'}, {'doc_number': '11158344', 'country': 'US', 'kind': 'B1'}, {'doc_number': '2022150402', 'country': 'US', 'kind': 'A1'}, {'doc_number': '11350029', 'country': 'US', 'kind': 'B1'}]

In [5]:
family = client.family(
    reference_type="application",    
    input=models.Docdb("22179301", "EP", "A"),  # input=models.Docdb("09164213", "EP", "A"), # input=models.Docdb("2101496", "EP", "B1"), # input=models.Docdb("2792747", "EP", "A1"), 
    constituents=["biblio", "legal"],
    output_type="dataframe",
)

# Print the columns to see if document details are present
print(family.columns)

# Check if document details are present in the DataFrame
if all(col in family.columns for col in ['ops:publication-reference|document-id|doc-number', 
                                         'ops:publication-reference|document-id|country', 
                                         'ops:publication-reference|document-id|kind']):
    # Extract relevant document details and remove duplicates
    document_details = family[['ops:publication-reference|document-id|doc-number', 
                               'ops:publication-reference|document-id|country', 
                               'ops:publication-reference|document-id|kind']].drop_duplicates()

    # Rename columns for easier readability
    document_details.columns = ['Document Number', 'Country', 'Kind']
    
    # Print document details
    print(document_details)
else:
    print("Document details not found in DataFrame")

# Reset to default options if needed with pd.reset_option('display.max_colwidth')
pd.set_option('display.max_colwidth', 2000)

family

Index(['legal', 'total-result-count', 'ops:family-member|family-id',
       'ops:family-member|publication-reference',
       'ops:family-member|application-reference',
       'ops:family-member|priority-claim', 'ops:family-member|ops:legal',
       'ops:family-member|exchange-document',
       'ops:application-reference|document-id|document-id-type',
       'ops:application-reference|document-id|country',
       'ops:application-reference|document-id|doc-number',
       'ops:application-reference|document-id|kind'],
      dtype='object')
Document details not found in DataFrame

,legal,total-result-count,ops:family-member|family-id,ops:family-member|publication-reference,ops:family-member|application-reference,ops:family-member|priority-claim,ops:family-member|ops:legal,ops:family-member|exchange-document,ops:application-reference|document-id|document-id-type,ops:application-reference|document-id|country,ops:application-reference|document-id|doc-number,ops:application-reference|document-id|kind
0,true,2,82067485,"{'document-id': [{'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '4106326', 'kind': 'A1', 'date': '20221221'}, {'@document-id-type': 'epodoc', 'doc-number': 'EP4106326', 'date': '20221221'}]}","{'@doc-id': '574299984', '@is-representative': 'YES', 'document-id': {'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '22179301', 'kind': 'A', 'date': '20220615'}}","[{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202163202527', 'kind': 'P', 'date': '20210615'}, 'priority-active-indicator': 'YES'}]","[{'@code': 'AK ', '@desc': 'DESIGNATED CONTRACTING STATES', '@infl': '+', '@dateMigr': '00010101', 'ops:pre': [{'@line': '00001', '#text': 'EP 22179301A 2022-12-21AK +DESIGNATED CONTRACTING STATES Kind Code of Ref Document A1'}, {'@line': '00002', '#text': 'EP 22179301A 2022-12-21AK +DESIGNATED CONTRACTING STATES Designated State(s) AL AT BE BG CH CY CZ DE DK EE ES FI FR GB GR HR HU IE IS IT LI LT LU LV MC MK MT NL NO PL PT RO RS SE SI SK SM TR'}], 'ops:L001EP': {'@desc': 'Country Code', '#text': 'EP'}, 'ops:L002EP': {'@desc': 'Filing / Published Document', '#text': 'F'}, 'ops:L003EP': {'@desc': 'Document Number', '#text': '22179301'}, 'ops:L004EP': {'@desc': 'Kind Code', '#text': 'A'}, 'ops:L005EP': {'@desc': 'IPR Type', '#text': 'PI'}, 'ops:L007EP': {'@desc': 'Gazette DATE', '#text': '2022-12-21'}, 'ops:L008EP': {'@desc': 'Legal Event Code 1', '#text': 'AK'}, 'ops:L018EP': {'@desc': 'DATE last exchanged', '#text': '2022-12-24'}, 'ops:L019EP': {'@desc': 'DATE first created', '#text': '2022-12-21'}, 'ops:L500EP': {'ops:L506EP': {'@desc': 'Kind Code of Ref Document', '#text': 'A1'}, 'ops:L507EP': {'@desc': 'Designated State(s)', '#text': 'AL AT BE BG CH CY CZ DE DK EE ES FI FR GB GR HR HU IE IS IT LI LT LU LV MC MK MT NL NO PL PT RO RS SE SI SK SM TR'}}}, {'@code': 'PUAI', '@desc': 'PUBLIC REFERENCE MADE UNDER ARTICLE 153(3) EPC TO A PUBLISHED INTERNATIONAL APPLICATION THAT HAS ENTERED THE EUROPEAN PHASE', '@infl': ' ', '@dateMigr': '00010101', 'ops:pre': {'@line': '00001', '#text': 'EP 22179301A 2022-11-18PUAI PUBLIC REFERENCE MADE UNDER ARTICLE 153(3) EPC TO A PUBLISHED INTERNATIONAL APPLICATION THAT HAS ENTERED THE EUROPEAN PHASE Free Format Text ORIGINAL CODE: 0009012'}, 'ops:L001EP': {'@desc': 'Country Code', '#text': 'EP'}, 'ops:L002EP': {'@desc': 'Filing / Published Document', '#text': 'F'}, 'ops:L003EP': {'@desc': 'Document Number', '#text': '22179301'}, 'ops:L004EP': {'@desc': 'Kind Code', '#text': 'A'}, 'ops:L005EP': {'@desc': 'IPR Type',...","{'@system': 'ops.epo.org', '@family-id': '82067485', '@country': 'EP', '@doc-number': '4106326', '@kind': 'A1', 'bibliographic-data': {'publication-reference': {'document-id': [{'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '4106326', 'kind': 'A1', 'date': '20221221'}, {'@document-id-type': 'epodoc', 'doc-number': 'EP4106326', 'date': '20221221'}]}, 'classifications-ipcr': {'classification-ipcr': {'@sequence': '1', 'text': 'H04N 7/ 14 A I'}}, 'patent-classifications': {'patent-classification': [{'@sequence': '1', 'classification-scheme': {'@office': 'EP', '@scheme': 'CPCI'}, 'section': 'H', 'class': '04', 'subclass': 'N', 'main-group': '7', 'subgroup': '147', 'classification-value': 'I', 'generating-office': 'US'}, {'@sequence': '2', 'classification-scheme': {'@office': 'EP', '@scheme': 'CPCI'}, 'section': 'H', 'class': '04', 'subclass': 'N', 'main-group': '7', 'subgroup': '147', 'classification-value': 'I', 'generating-office': 'EP'}, {'@sequence': '3', 'classification-scheme': {'@office': 'EP', '@scheme': 'CPCI'}, 'section': 'H', 'class': '04', 'subclass': 'N', 'main-group': '7', 'subgroup': '15', 'classification-value': 'I', 'generating-office': 'US'}, {'@sequence': '4', 'classification-scheme': {'@office': 'EP', '@scheme': 'CPCI'}, 'section': 'H', 'class': '04', 'subclass': 'N', 'main-group': '13', 'subgroup': '204', 'classification-value': 'I', 'generating-office': 'US'}, {'@sequence': '5', 'classification-scheme': {'@office': 'EP', '@scheme': 'CPCI'}, 'section': 'H', 'class': '04', 'subclass': 'N', 'main-group': '23', 'subgroup': '695', 'classification-value': 'I', 'generating-office': 'US'}, {'@sequence': '6', 'classification-scheme': {'@office': 'EP', '@scheme': 'CPCI'}, 'section': 'H', 'class': '04', 'subclass': 'N', 'main-group': '23', 'subgroup': '90', 'classification-value': 'I', 'generating-office': 'US'}]}, 'application-reference': {'@doc-id': '574299984', 'document-id': [{'@document-id-type': 'docdb', 'country': 'EP'...",docdb,EP,22179301,A
1,true,2,82067485,"{'document-id': [{'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '2022400244', 'kind': 'A1', 'date': '20221215'}, {'@document-id-type': 'epodoc', 'doc-number': 'US2022400244', 'date': '20221215'}]}","{'@doc-id': '584535325', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}}","[{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202163202527', 'kind': 'P', 'date': '20210615'}, 'priority-active-indicator': 'YES'}]","[{'@code': 'AS ', '@desc': 'ASSIGNMENT', '@infl': ' ', '@dateMigr': '00010101', 'ops:pre': [{'@line': '00001', '#text': 'US202217806216A 2022-06-27AS ASSIGNMENT OWNER PLANTRONICS, INC., CALIFORNIA'}, {'@line': '00002', '#text': 'US202217806216A 2022-06-27AS ASSIGNMENT Free Format Text ASSIGNMENT OF ASSIGNORS INTEREST;ASSIGNORS:SCHAEFER, STEPHEN PAUL;CHILDRESS, ROMMEL GABRIEL, JR;SIGNING DATES FROM 20220608 TO 20220609;REEL/FRAME:060322/0909'}], 'ops:L001EP': {'@desc': 'Country Code', '#text': 'US'}, 'ops:L002EP': {'@desc': 'Filing / Published Document', '#text': 'F'}, 'ops:L003EP': {'@desc': 'Document Number', '#text': '202217806216'}, 'ops:L004EP': {'@desc': 'Kind Code', '#text': 'A'}, 'ops:L005EP': {'@desc': 'IPR Type', '#text': 'PI'}, 'ops:L007EP': {'@desc': 'Gazette DATE', '#text': '2022-06-27'}, 'ops:L008EP': {'@desc': 'Legal Event Code 1', '#text': 'AS'}, 'ops:L018EP': {'@desc': 'DATE last exchanged', '#text': '2022-12-24'}, 'ops:L019EP': {'@desc': 'DATE first created', '#text': '2022-12-21'}, 'ops:L500EP': {'ops:L509EP': {'@desc': 'OWNER', '#text': 'PLANTRONICS, INC., CALIFORNIA'}, 'ops:L510EP': {'@desc': 'Free Format Text', '#text': 'ASSIGNMENT OF ASSIGNORS INTEREST;ASSIGNORS:SCHAEFER, STEPHEN PAUL;CHILDRESS, ROMMEL GABRIEL, JR;SIGNING DATES FROM 20220608 TO 20220609;REEL/FRAME:060322/0909'}}}, {'@code': 'STPP', '@desc': 'INFORMATION ON STATUS: PATENT APPLICATION AND GRANTING PROCEDURE IN GENERAL', '@infl': ' ', '@dateMigr': '00010101', 'ops:pre': {'@line': '00001', '#text': 'US202217806216A 2022-07-18STPP INFORMATION ON STATUS: PATENT APPLICATION AND GRANTING PROCEDURE IN GENERAL Free Format Text DOCKETED NEW CASE - READY FOR EXAMINATION'}, 'ops:L001EP': {'@desc': 'Country Code', '#text': 'US'}, 'ops:L002EP': {'@desc': 'Filing / Published Document', '#text': 'F'}, 'ops:L003EP': {'@desc': 'Document Number', '#text': '202217806216'}, 'ops:L004EP': {'@desc': 'Kind Code', '#text': 'A'}, 'ops:L005EP': {'@desc': 'IPR Type', '#text': 'PI'}, 'ops:L007EP...","{'@system': 'ops.epo.org', '@family-id': '82067485', '@country': 'US', '@doc-number': '2022400244', '@kind': 'A1', 'bibliographic-data': {'publication-reference': {'document-id': [{'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '2022400244', 'kind': 'A1', 'date': '20221215'}, {'@document-id-type': 'epodoc', 'doc-number': 'US2022400244', 'date': '20221215'}]}, 'classifications-ipcr': {'classification-ipcr': [{'@sequence': '1', 'text': 'H04N 7/ 15 A I'}, {'@sequence': '2', 'text': 'H04N 7/ 18 A I'}, {'@sequence': '3', 'text': 'H04N 13/ 204 A I'}, {'@sequence': '4', 'text': 'H04N 13/ 354 A I'}]}, 'patent-classifications': {'patent-classification': [{'@sequence': '1', 'classification-scheme': {'@office': 'EP', '@scheme': 'CPCI'}, 'section': 'H', 'class': '04', 'subclass': 'N', 'main-group': '7', 'subgroup': '147', 'classification-value': 'I', 'generating-office': 'US'}, {'@sequence': '2', 'classification-scheme': {'@office': 'EP', '@scheme': 'CPCI'}, 'section': 'H', 'class': '04', 'subclass': 'N', 'main-group': '7', 'subgroup': '147', 'classification-value': 'I', 'generating-office': 'EP'}, {'@sequence': '3', 'classification-scheme': {'@office': 'EP', '@scheme': 'CPCI'}, 'section': 'H', 'class': '04', 'subclass': 'N', 'main-group': '7', 'subgroup': '15', 'classification-value': 'I', 'generating-office': 'US'}, {'@sequence': '4', 'classification-scheme': {'@office': 'EP', '@scheme': 'CPCI'}, 'section': 'H', 'class': '04', 'subclass': 'N', 'main-group': '13', 'subgroup': '204', 'classification-value': 'I', 'generating-office': 'US'}, {'@sequence': '5', 'classification-scheme': {'@office': 'EP', '@scheme': 'CPCI'}, 'section': 'H', 'class': '04', 'subclass': 'N', 'main-group': '23', 'subgroup': '695', 'classification-value': 'I', 'generating-office': 'US'}, {'@sequence': '6', 'classification-scheme': {'@office': 'EP', '@scheme': 'CPCI'}, 'section': 'H', 'class': '04', 'subclass': 'N', 'main-group'...",docdb,EP,22179301,A

#### 7.2.3	Example of fetching bibliographic data and legal data of a family 
* by retrieving the bibliographic data of the application
* and by retrieving the legal data of the publication
* before combining them

#### 7.2.3.1 The bibliographic data and the legal data are derived from the family of ```"22179301", "EP", "A"``` and ```"4106326", "EP", "A1"``` as stored in Docdb.

In [6]:
import pandas as pd

# Reset to default options if needed with pd.reset_option('display.max_colwidth')
pd.set_option('display.max_colwidth', 2000)

# Fetch bibliographic data for published patent application
family1 = client.family(
    reference_type="application",  # publication, application, priority
    input=models.Docdb("22179301", "EP", "A"),  # original, docdb, epodoc
    constituents=None,
    output_type="Dataframe"  # optional, xml or DataFrame format
)
display(family1)

family2 = client.family(
    reference_type="publication",  # publication, application, priority
    input=models.Docdb("4106326", "EP", "A1"),  # original, docdb, epodoc
    constituents=["legal"],
    output_type="Dataframe"  # optional, xml or DataFrame format
)
display(family2)

# # Inspect the columns
print("Family1 Columns:", family1.columns)
print("Family2 Columns:", family2.columns)

# Print the number of rows in each DataFrame
print(f"Number of rows in family1: {len(family1)}")
print(f"Number of rows in family2: {len(family2)}")

,legal,total-result-count,ops:family-member|family-id,ops:family-member|publication-reference,ops:family-member|application-reference,ops:family-member|priority-claim,ops:application-reference|document-id|document-id-type,ops:application-reference|document-id|country,ops:application-reference|document-id|doc-number,ops:application-reference|document-id|kind
0,false,2,82067485,"{'document-id': [{'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '4106326', 'kind': 'A1', 'date': '20221221'}, {'@document-id-type': 'epodoc', 'doc-number': 'EP4106326', 'date': '20221221'}]}","{'@doc-id': '574299984', '@is-representative': 'YES', 'document-id': {'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '22179301', 'kind': 'A', 'date': '20220615'}}","[{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202163202527', 'kind': 'P', 'date': '20210615'}, 'priority-active-indicator': 'YES'}]",docdb,EP,22179301,A
1,false,2,82067485,"{'document-id': [{'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '2022400244', 'kind': 'A1', 'date': '20221215'}, {'@document-id-type': 'epodoc', 'doc-number': 'US2022400244', 'date': '20221215'}]}","{'@doc-id': '584535325', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}}","[{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202163202527', 'kind': 'P', 'date': '20210615'}, 'priority-active-indicator': 'YES'}]",docdb,EP,22179301,A

,legal,total-result-count,ops:family-member|family-id,ops:family-member|publication-reference,ops:family-member|application-reference,ops:family-member|priority-claim,ops:family-member|ops:legal,ops:publication-reference|document-id|document-id-type,ops:publication-reference|document-id|country,ops:publication-reference|document-id|doc-number,ops:publication-reference|document-id|kind
0,true,2,82067485,"{'document-id': [{'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '4106326', 'kind': 'A1', 'date': '20221221'}, {'@document-id-type': 'epodoc', 'doc-number': 'EP4106326', 'date': '20221221'}]}","{'@doc-id': '574299984', '@is-representative': 'YES', 'document-id': {'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '22179301', 'kind': 'A', 'date': '20220615'}}","[{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202163202527', 'kind': 'P', 'date': '20210615'}, 'priority-active-indicator': 'YES'}]","[{'@code': 'AK ', '@desc': 'DESIGNATED CONTRACTING STATES', '@infl': '+', '@dateMigr': '00010101', 'ops:pre': [{'@line': '00001', '#text': 'EP 22179301A 2022-12-21AK +DESIGNATED CONTRACTING STATES Kind Code of Ref Document A1'}, {'@line': '00002', '#text': 'EP 22179301A 2022-12-21AK +DESIGNATED CONTRACTING STATES Designated State(s) AL AT BE BG CH CY CZ DE DK EE ES FI FR GB GR HR HU IE IS IT LI LT LU LV MC MK MT NL NO PL PT RO RS SE SI SK SM TR'}], 'ops:L001EP': {'@desc': 'Country Code', '#text': 'EP'}, 'ops:L002EP': {'@desc': 'Filing / Published Document', '#text': 'F'}, 'ops:L003EP': {'@desc': 'Document Number', '#text': '22179301'}, 'ops:L004EP': {'@desc': 'Kind Code', '#text': 'A'}, 'ops:L005EP': {'@desc': 'IPR Type', '#text': 'PI'}, 'ops:L007EP': {'@desc': 'Gazette DATE', '#text': '2022-12-21'}, 'ops:L008EP': {'@desc': 'Legal Event Code 1', '#text': 'AK'}, 'ops:L018EP': {'@desc': 'DATE last exchanged', '#text': '2022-12-24'}, 'ops:L019EP': {'@desc': 'DATE first created', '#text': '2022-12-21'}, 'ops:L500EP': {'ops:L506EP': {'@desc': 'Kind Code of Ref Document', '#text': 'A1'}, 'ops:L507EP': {'@desc': 'Designated State(s)', '#text': 'AL AT BE BG CH CY CZ DE DK EE ES FI FR GB GR HR HU IE IS IT LI LT LU LV MC MK MT NL NO PL PT RO RS SE SI SK SM TR'}}}, {'@code': 'PUAI', '@desc': 'PUBLIC REFERENCE MADE UNDER ARTICLE 153(3) EPC TO A PUBLISHED INTERNATIONAL APPLICATION THAT HAS ENTERED THE EUROPEAN PHASE', '@infl': ' ', '@dateMigr': '00010101', 'ops:pre': {'@line': '00001', '#text': 'EP 22179301A 2022-11-18PUAI PUBLIC REFERENCE MADE UNDER ARTICLE 153(3) EPC TO A PUBLISHED INTERNATIONAL APPLICATION THAT HAS ENTERED THE EUROPEAN PHASE Free Format Text ORIGINAL CODE: 0009012'}, 'ops:L001EP': {'@desc': 'Country Code', '#text': 'EP'}, 'ops:L002EP': {'@desc': 'Filing / Published Document', '#text': 'F'}, 'ops:L003EP': {'@desc': 'Document Number', '#text': '22179301'}, 'ops:L004EP': {'@desc': 'Kind Code', '#text': 'A'}, 'ops:L005EP': {'@desc': 'IPR Type',...",docdb,EP,4106326,A1
1,true,2,82067485,"{'document-id': [{'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '2022400244', 'kind': 'A1', 'date': '20221215'}, {'@document-id-type': 'epodoc', 'doc-number': 'US2022400244', 'date': '20221215'}]}","{'@doc-id': '584535325', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}}","[{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202163202527', 'kind': 'P', 'date': '20210615'}, 'priority-active-indicator': 'YES'}]","[{'@code': 'AS ', '@desc': 'ASSIGNMENT', '@infl': ' ', '@dateMigr': '00010101', 'ops:pre': [{'@line': '00001', '#text': 'US202217806216A 2022-06-27AS ASSIGNMENT OWNER PLANTRONICS, INC., CALIFORNIA'}, {'@line': '00002', '#text': 'US202217806216A 2022-06-27AS ASSIGNMENT Free Format Text ASSIGNMENT OF ASSIGNORS INTEREST;ASSIGNORS:SCHAEFER, STEPHEN PAUL;CHILDRESS, ROMMEL GABRIEL, JR;SIGNING DATES FROM 20220608 TO 20220609;REEL/FRAME:060322/0909'}], 'ops:L001EP': {'@desc': 'Country Code', '#text': 'US'}, 'ops:L002EP': {'@desc': 'Filing / Published Document', '#text': 'F'}, 'ops:L003EP': {'@desc': 'Document Number', '#text': '202217806216'}, 'ops:L004EP': {'@desc': 'Kind Code', '#text': 'A'}, 'ops:L005EP': {'@desc': 'IPR Type', '#text': 'PI'}, 'ops:L007EP': {'@desc': 'Gazette DATE', '#text': '2022-06-27'}, 'ops:L008EP': {'@desc': 'Legal Event Code 1', '#text': 'AS'}, 'ops:L018EP': {'@desc': 'DATE last exchanged', '#text': '2022-12-24'}, 'ops:L019EP': {'@desc': 'DATE first created', '#text': '2022-12-21'}, 'ops:L500EP': {'ops:L509EP': {'@desc': 'OWNER', '#text': 'PLANTRONICS, INC., CALIFORNIA'}, 'ops:L510EP': {'@desc': 'Free Format Text', '#text': 'ASSIGNMENT OF ASSIGNORS INTEREST;ASSIGNORS:SCHAEFER, STEPHEN PAUL;CHILDRESS, ROMMEL GABRIEL, JR;SIGNING DATES FROM 20220608 TO 20220609;REEL/FRAME:060322/0909'}}}, {'@code': 'STPP', '@desc': 'INFORMATION ON STATUS: PATENT APPLICATION AND GRANTING PROCEDURE IN GENERAL', '@infl': ' ', '@dateMigr': '00010101', 'ops:pre': {'@line': '00001', '#text': 'US202217806216A 2022-07-18STPP INFORMATION ON STATUS: PATENT APPLICATION AND GRANTING PROCEDURE IN GENERAL Free Format Text DOCKETED NEW CASE - READY FOR EXAMINATION'}, 'ops:L001EP': {'@desc': 'Country Code', '#text': 'US'}, 'ops:L002EP': {'@desc': 'Filing / Published Document', '#text': 'F'}, 'ops:L003EP': {'@desc': 'Document Number', '#text': '202217806216'}, 'ops:L004EP': {'@desc': 'Kind Code', '#text': 'A'}, 'ops:L005EP': {'@desc': 'IPR Type', '#text': 'PI'}, 'ops:L007EP...",docdb,EP,4106326,A1

Family1 Columns: Index(['legal', 'total-result-count', 'ops:family-member|family-id',
       'ops:family-member|publication-reference',
       'ops:family-member|application-reference',
       'ops:family-member|priority-claim',
       'ops:application-reference|document-id|document-id-type',
       'ops:application-reference|document-id|country',
       'ops:application-reference|document-id|doc-number',
       'ops:application-reference|document-id|kind'],
      dtype='object')
Family2 Columns: Index(['legal', 'total-result-count', 'ops:family-member|family-id',
       'ops:family-member|publication-reference',
       'ops:family-member|application-reference',
       'ops:family-member|priority-claim', 'ops:family-member|ops:legal',
       'ops:publication-reference|document-id|document-id-type',
       'ops:publication-reference|document-id|country',
       'ops:publication-reference|document-id|doc-number',
       'ops:publication-reference|document-id|kind'],
      dtype='object')
Number of rows in family1: 2
Number of rows in family2: 2

#### 7.2.3.2 Combining Family1 and Family2 dataframes 
* defining the common column to Family1 and Family2 dataframes: 'ops:family-member|family-id'
* Perform an outer join to diagnose missing keys
* Print the combined DataFrame with the outer join
* Show how many rows are in each category (both, left_only, right_only)
* Display rows with mismatched keys
* Perform the actual merge using inner join
* Display the combined DataFrame

In [7]:
# Assuming the common column to Family1 and Family2 dataframes is 'ops:family-member|family-id'
common_column = 'ops:family-member|family-id'

# Perform an outer join to diagnose missing keys
combined_family_outer = pd.merge(family1, family2, on=common_column, how='outer', indicator=True)

# Print the combined DataFrame with the outer join
print(combined_family_outer[:5])

# Show how many rows are in each category (both, left_only, right_only)
print(combined_family_outer['_merge'].value_counts()[:5])

# Display rows with mismatched keys
print(combined_family_outer[combined_family_outer['_merge'] != 'both'])

# Perform the actual merge using inner join
combined_family = pd.merge(family1, family2, on=common_column, how='inner')

# Display the combined DataFrame
combined_family

  legal_x total-result-count_x ops:family-member|family-id  \
0   false                    2                    82067485
1   false                    2                    82067485
2   false                    2                    82067485
3   false                    2                    82067485

                                                                                                                                                                             ops:family-member|publication-reference_x  \
0        {'document-id': [{'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '4106326', 'kind': 'A1', 'date': '20221221'}, {'@document-id-type': 'epodoc', 'doc-number': 'EP4106326', 'date': '20221221'}]}
1        {'document-id': [{'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '4106326', 'kind': 'A1', 'date': '20221221'}, {'@document-id-type': 'epodoc', 'doc-number': 'EP4106326', 'date': '20221221'}]}
2  {'document-id': [{'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '2022400244', 'kind': 'A1', 'date': '20221215'}, {'@document-id-type': 'epodoc', 'doc-number': 'US2022400244', 'date': '20221215'}]}
3  {'document-id': [{'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '2022400244', 'kind': 'A1', 'date': '20221215'}, {'@document-id-type': 'epodoc', 'doc-number': 'US2022400244', 'date': '20221215'}]}

                                                                                                                                          ops:family-member|application-reference_x  \
0  {'@doc-id': '574299984', '@is-representative': 'YES', 'document-id': {'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '22179301', 'kind': 'A', 'date': '20220615'}}
1  {'@doc-id': '574299984', '@is-representative': 'YES', 'document-id': {'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '22179301', 'kind': 'A', 'date': '20220615'}}
2                           {'@doc-id': '584535325', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}}
3                           {'@doc-id': '584535325', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}}

                                                                                                                                                                                                                                                                                                                                                                                         ops:family-member|priority-claim_x  \
0  [{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202163202527', 'kind': 'P', 'date': '20210615'}, 'priority-active-indicator': 'YES'}]
1  [{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202163202527', 'kind': 'P', 'date': '20210615'}, 'priority-active-indicator': 'YES'}]
2  [{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202163202527', 'kind': 'P', 'date': '20210615'}, 'priority-active-indicator': 'YES'}]
3  [{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202163202527', 'kind': 'P', 'date': '20210615'}, 'priority-active-indicator': 'YES'}]

  ops:application-reference|document-id|document-id-type  \
0                                                  docdb
1                                                  docdb
2                                                  docdb
3                                                  docdb

  ops:application-reference|document-id|country  \
0                                            EP
1                                            EP
2                                            EP
3                                            EP

  ops:application-reference|document-id|doc-number  \
0                                         22179301
1                                         22179301
2                                         22179301
3                                         22179301

  ops:application-reference|document-id|kind  ... total-result-count_y  \
0                                          A  ...                    2
1                                          A  ...                    2
2                                          A  ...                    2
3                                          A  ...                    2

                                                                                                                                                                             ops:family-member|publication-reference_y  \
0        {'document-id': [{'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '4106326', 'kind': 'A1', 'date': '20221221'}, {'@document-id-type': 'epodoc', 'doc-number': 'EP4106326', 'date': '20221221'}]}
1  {'document-id': [{'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '2022400244', 'kind': 'A1', 'date': '20221215'}, {'@document-id-type': 'epodoc', 'doc-number': 'US2022400244', 'date': '20221215'}]}
2        {'document-id': [{'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '4106326', 'kind': 'A1', 'date': '20221221'}, {'@document-id-type': 'epodoc', 'doc-number': 'EP4106326', 'date': '20221221'}]}
3  {'document-id': [{'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '2022400244', 'kind': 'A1', 'date': '20221215'}, {'@document-id-type': 'epodoc', 'doc-number': 'US2022400244', 'date': '20221215'}]}

                                                                                                                                          ops:family-member|application-reference_y  \
0  {'@doc-id': '574299984', '@is-representative': 'YES', 'document-id': {'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '22179301', 'kind': 'A', 'date': '20220615'}}
1                           {'@doc-id': '584535325', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}}
2  {'@doc-id': '574299984', '@is-representative': 'YES', 'document-id': {'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '22179301', 'kind': 'A', 'date': '20220615'}}
3                           {'@doc-id': '584535325', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}}

                                                                                                                                                                                                                                                                                                                                                                                         ops:family-member|priority-claim_y  \
0  [{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202163202527', 'kind': 'P', 'date': '20210615'}, 'priority-active-indicator': 'YES'}]
1  [{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202163202527', 'kind': 'P', 'date': '20210615'}, 'priority-active-indicator': 'YES'}]
2  [{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202163202527', 'kind': 'P', 'date': '20210615'}, 'priority-active-indicator': 'YES'}]
3  [{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202163202527', 'kind': 'P', 'date': '20210615'}, 'priority-active-indicator': 'YES'}]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ops:family-member|ops:legal  \
0  [{'@code': 'AK  ', '@desc': 'DESIGNATED CONTRACTING STATES', '@infl': '+', '@dateMigr': '00010101', 'ops:pre': [{'@line': '00001', '#text': 'EP    22179301A  2022-12-21AK  +DESIGNATED CONTRACTING STATES Kind Code of Ref Document A1'}, {'@line': '00002', '#text': 'EP    22179301A  2022-12-21AK  +DESIGNATED CONTRACTING STATES Designated State(s) AL AT BE BG CH CY CZ DE DK EE ES FI FR GB GR HR HU IE IS IT LI LT LU LV MC MK MT NL NO PL PT RO RS SE SI SK SM TR'}], 'ops:L001EP': {'@desc': 'Country Code', '#text': 'EP'}, 'ops:L002EP': {'@desc': 'Filing / Published Document', '#text': 'F'}, 'ops:L003EP': {'@desc': 'Document Number', '#text': '22179301'}, 'ops:L004EP': {'@desc': 'Kind Code', '#text': 'A'}, 'ops:L005EP': {'@desc': 'IPR Type', '#text': 'PI'}, 'ops:L007EP': {'@desc': 'Gazette DATE', '#text': '2022-12-21'}, 'ops:L008EP': {'@desc': 'Legal Event Code 1', '#text': 'AK'}, 'ops:L018EP': {'@desc': 'DATE last exchanged', '#text': '2022-12-24'}, 'ops:L019EP': {'@desc': 'DATE first created', '#text': '2022-12-21'}, 'ops:L500EP': {'ops:L506EP': {'@desc': 'Kind Code of Ref Document', '#text': 'A1'}, 'ops:L507EP': {'@desc': 'Designated State(s)', '#text': 'AL AT BE BG CH CY CZ DE DK EE ES FI FR GB GR HR HU IE IS IT LI LT LU LV MC MK MT NL NO PL PT RO RS SE SI SK SM TR'}}}, {'@code': 'PUAI', '@desc': 'PUBLIC REFERENCE MADE UNDER ARTICLE 153(3) EPC TO A PUBLISHED INTERNATIONAL APPLICATION THAT HAS ENTERED THE EUROPEAN PHASE', '@infl': ' ', '@dateMigr': '00010101', 'ops:pre': {'@line': '00001', '#text': 'EP    22179301A  2022-11-18PUAI PUBLIC REFERENCE MADE UNDER ARTICLE 153(3) EPC TO A PUBLISHED INTERNATIONAL APPLICATION THAT HAS ENTERED THE EUROPEAN PHASE Free Format Text ORIGINAL CODE: 0009012'}, 'ops:L001EP': {'@desc': 'Country Code', '#text': 'EP'}, 'ops:L002EP': {'@desc': 'Filing / Published Document', '#text': 'F'}, 'ops:L003EP': {'@desc': 'Document Number', '#text': '22179301'}, 'ops:L004EP': {'@desc': 'Kind Code', '#text': 'A'}, 'ops:L005EP': {'@desc': 'IPR Type',...
1  [{'@code': 'AS  ', '@desc': 'ASSIGNMENT', '@infl': ' ', '@dateMigr': '00010101', 'ops:pre': [{'@line': '00001', '#text': 'US202217806216A  2022-06-27AS   ASSIGNMENT OWNER PLANTRONICS, INC., CALIFORNIA'}, {'@line': '00002', '#text': 'US202217806216A  2022-06-27AS   ASSIGNMENT Free Format Text ASSIGNMENT OF ASSIGNORS INTEREST;ASSIGNORS:SCHAEFER, STEPHEN PAUL;CHILDRESS, ROMMEL GABRIEL, JR;SIGNING DATES FROM 20220608 TO 20220609;REEL/FRAME:060322/0909'}], 'ops:L001EP': {'@desc': 'Country Code', '#text': 'US'}, 'ops:L002EP': {'@desc': 'Filing / Published Document', '#text': 'F'}, 'ops:L003EP': {'@desc': 'Document Number', '#text': '202217806216'}, 'ops:L004EP': {'@desc': 'Kind Code', '#text': 'A'}, 'ops:L005EP': {'@desc': 'IPR Type', '#text': 'PI'}, 'ops:L007EP': {'@desc': 'Gazette DATE', '#text': '2022-06-27'}, 'ops:L008EP': {'@desc': 'Legal Event Code 1', '#text': 'AS'}, 'ops:L018EP': {'@desc': 'DATE last exchanged', '#text': '2022-12-24'}, 'ops:L019EP': {'@desc': 'DATE first created', '#text': '2022-12-21'}, 'ops:L500EP': {'ops:L509EP': {'@desc': 'OWNER', '#text': 'PLANTRONICS, INC., CALIFORNIA'}, 'ops:L510EP': {'@desc': 'Free Format Text', '#text': 'ASSIGNMENT OF ASSIGNORS INTEREST;ASSIGNORS:SCHAEFER, STEPHEN PAUL;CHILDRESS, ROMMEL GABRIEL, JR;SIGNING DATES FROM 20220608 TO 20220609;REEL/FRAME:060322/0909'}}}, {'@code': 'STPP', '@desc': 'INFORMATION ON STATUS: PATENT APPLICATION AND GRANTING PROCEDURE IN GENERAL', '@infl': ' ', '@dateMigr': '00010101', 'ops:pre': {'@line': '00001', '#text': 'US202217806216A  2022-07-18STPP INFORMATION ON STATUS: PATENT APPLICATION AND GRANTING PROCEDURE IN GENERAL Free Format Text DOCKETED NEW CASE - READY FOR EXAMINATION'}, 'ops:L001EP': {'@desc': 'Country Code', '#text': 'US'}, 'ops:L002EP': {'@desc': 'Filing / Published Document', '#text': 'F'}, 'ops:L003EP': {'@desc': 'Document Number', '#text': '202217806216'}, 'ops:L004EP': {'@desc': 'Kind Code', '#text': 'A'}, 'ops:L005EP': {'@desc': 'IPR Type', '#text': 'PI'}, 'ops:L007EP...
2  [{'@code': 'AK  ', '@desc': 'DESIGNATED CONTRACTING STATES', '@infl': '+', '@dateMigr': '00010101', 'ops:pre': [{'@line': '00001', '#text': 'EP    22179301A  2022-12-21AK  +DESIGNATED CONTRACTING STATES Kind Code of Ref Document A1'}, {'@line': '00002', '#text': 'EP    22179301A  2022-12-21AK  +DESIGNATED CONTRACTING STATES Designated State(s) AL AT BE BG CH CY CZ DE DK EE ES FI FR GB GR HR HU IE IS IT LI LT LU LV MC MK MT NL NO PL PT RO RS SE SI SK SM TR'}], 'ops:L001EP': {'@desc': 'Country Code', '#text': 'EP'}, 'ops:L002EP': {'@desc': 'Filing / Published Document', '#text': 'F'}, 'ops:L003EP': {'@desc': 'Document Number', '#text': '22179301'}, 'ops:L004EP': {'@desc': 'Kind Code', '#text': 'A'}, 'ops:L005EP': {'@desc': 'IPR Type', '#text': 'PI'}, 'ops:L007EP': {'@desc': 'Gazette DATE', '#text': '2022-12-21'}, 'ops:L008EP': {'@desc': 'Legal Event Code 1', '#text': 'AK'}, 'ops:L018EP': {'@desc': 'DATE last exchanged', '#text': '2022-12-24'}, 'ops:L019EP': {'@desc': 'DATE first created', '#text': '2022-12-21'}, 'ops:L500EP': {'ops:L506EP': {'@desc': 'Kind Code of Ref Document', '#text': 'A1'}, 'ops:L507EP': {'@desc': 'Designated State(s)', '#text': 'AL AT BE BG CH CY CZ DE DK EE ES FI FR GB GR HR HU IE IS IT LI LT LU LV MC MK MT NL NO PL PT RO RS SE SI SK SM TR'}}}, {'@code': 'PUAI', '@desc': 'PUBLIC REFERENCE MADE UNDER ARTICLE 153(3) EPC TO A PUBLISHED INTERNATIONAL APPLICATION THAT HAS ENTERED THE EUROPEAN PHASE', '@infl': ' ', '@dateMigr': '00010101', 'ops:pre': {'@line': '00001', '#text': 'EP    22179301A  2022-11-18PUAI PUBLIC REFERENCE MADE UNDER ARTICLE 153(3) EPC TO A PUBLISHED INTERNATIONAL APPLICATION THAT HAS ENTERED THE EUROPEAN PHASE Free Format Text ORIGINAL CODE: 0009012'}, 'ops:L001EP': {'@desc': 'Country Code', '#text': 'EP'}, 'ops:L002EP': {'@desc': 'Filing / Published Document', '#text': 'F'}, 'ops:L003EP': {'@desc': 'Document Number', '#text': '22179301'}, 'ops:L004EP': {'@desc': 'Kind Code', '#text': 'A'}, 'ops:L005EP': {'@desc': 'IPR Type',...
3  [{'@code': 'AS  ', '@desc': 'ASSIGNMENT', '@infl': ' ', '@dateMigr': '00010101', 'ops:pre': [{'@line': '00001', '#text': 'US202217806216A  2022-06-27AS   ASSIGNMENT OWNER PLANTRONICS, INC., CALIFORNIA'}, {'@line': '00002', '#text': 'US202217806216A  2022-06-27AS   ASSIGNMENT Free Format Text ASSIGNMENT OF ASSIGNORS INTEREST;ASSIGNORS:SCHAEFER, STEPHEN PAUL;CHILDRESS, ROMMEL GABRIEL, JR;SIGNING DATES FROM 20220608 TO 20220609;REEL/FRAME:060322/0909'}], 'ops:L001EP': {'@desc': 'Country Code', '#text': 'US'}, 'ops:L002EP': {'@desc': 'Filing / Published Document', '#text': 'F'}, 'ops:L003EP': {'@desc': 'Document Number', '#text': '202217806216'}, 'ops:L004EP': {'@desc': 'Kind Code', '#text': 'A'}, 'ops:L005EP': {'@desc': 'IPR Type', '#text': 'PI'}, 'ops:L007EP': {'@desc': 'Gazette DATE', '#text': '2022-06-27'}, 'ops:L008EP': {'@desc': 'Legal Event Code 1', '#text': 'AS'}, 'ops:L018EP': {'@desc': 'DATE last exchanged', '#text': '2022-12-24'}, 'ops:L019EP': {'@desc': 'DATE first created', '#text': '2022-12-21'}, 'ops:L500EP': {'ops:L509EP': {'@desc': 'OWNER', '#text': 'PLANTRONICS, INC., CALIFORNIA'}, 'ops:L510EP': {'@desc': 'Free Format Text', '#text': 'ASSIGNMENT OF ASSIGNORS INTEREST;ASSIGNORS:SCHAEFER, STEPHEN PAUL;CHILDRESS, ROMMEL GABRIEL, JR;SIGNING DATES FROM 20220608 TO 20220609;REEL/FRAME:060322/0909'}}}, {'@code': 'STPP', '@desc': 'INFORMATION ON STATUS: PATENT APPLICATION AND GRANTING PROCEDURE IN GENERAL', '@infl': ' ', '@dateMigr': '00010101', 'ops:pre': {'@line': '00001', '#text': 'US202217806216A  2022-07-18STPP INFORMATION ON STATUS: PATENT APPLICATION AND GRANTING PROCEDURE IN GENERAL Free Format Text DOCKETED NEW CASE - READY FOR EXAMINATION'}, 'ops:L001EP': {'@desc': 'Country Code', '#text': 'US'}, 'ops:L002EP': {'@desc': 'Filing / Published Document', '#text': 'F'}, 'ops:L003EP': {'@desc': 'Document Number', '#text': '202217806216'}, 'ops:L004EP': {'@desc': 'Kind Code', '#text': 'A'}, 'ops:L005EP': {'@desc': 'IPR Type', '#text': 'PI'}, 'ops:L007EP...

  ops:publication-reference|document-id|document-id-type  \
0                                                  docdb
1                                                  docdb
2                                                  docdb
3                                                  docdb

  ops:publication-reference|document-id|country  \
0                                            EP
1                                            EP

,legal_x,total-result-count_x,ops:family-member|family-id,ops:family-member|publication-reference_x,ops:family-member|application-reference_x,ops:family-member|priority-claim_x,ops:application-reference|document-id|document-id-type,ops:application-reference|document-id|country,ops:application-reference|document-id|doc-number,ops:application-reference|document-id|kind,legal_y,total-result-count_y,ops:family-member|publication-reference_y,ops:family-member|application-reference_y,ops:family-member|priority-claim_y,ops:family-member|ops:legal,ops:publication-reference|document-id|document-id-type,ops:publication-reference|document-id|country,ops:publication-reference|document-id|doc-number,ops:publication-reference|document-id|kind
0,false,2,82067485,"{'document-id': [{'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '4106326', 'kind': 'A1', 'date': '20221221'}, {'@document-id-type': 'epodoc', 'doc-number': 'EP4106326', 'date': '20221221'}]}","{'@doc-id': '574299984', '@is-representative': 'YES', 'document-id': {'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '22179301', 'kind': 'A', 'date': '20220615'}}","[{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202163202527', 'kind': 'P', 'date': '20210615'}, 'priority-active-indicator': 'YES'}]",docdb,EP,22179301,A,true,2,"{'document-id': [{'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '4106326', 'kind': 'A1', 'date': '20221221'}, {'@document-id-type': 'epodoc', 'doc-number': 'EP4106326', 'date': '20221221'}]}","{'@doc-id': '574299984', '@is-representative': 'YES', 'document-id': {'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '22179301', 'kind': 'A', 'date': '20220615'}}","[{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202163202527', 'kind': 'P', 'date': '20210615'}, 'priority-active-indicator': 'YES'}]","[{'@code': 'AK ', '@desc': 'DESIGNATED CONTRACTING STATES', '@infl': '+', '@dateMigr': '00010101', 'ops:pre': [{'@line': '00001', '#text': 'EP 22179301A 2022-12-21AK +DESIGNATED CONTRACTING STATES Kind Code of Ref Document A1'}, {'@line': '00002', '#text': 'EP 22179301A 2022-12-21AK +DESIGNATED CONTRACTING STATES Designated State(s) AL AT BE BG CH CY CZ DE DK EE ES FI FR GB GR HR HU IE IS IT LI LT LU LV MC MK MT NL NO PL PT RO RS SE SI SK SM TR'}], 'ops:L001EP': {'@desc': 'Country Code', '#text': 'EP'}, 'ops:L002EP': {'@desc': 'Filing / Published Document', '#text': 'F'}, 'ops:L003EP': {'@desc': 'Document Number', '#text': '22179301'}, 'ops:L004EP': {'@desc': 'Kind Code', '#text': 'A'}, 'ops:L005EP': {'@desc': 'IPR Type', '#text': 'PI'}, 'ops:L007EP': {'@desc': 'Gazette DATE', '#text': '2022-12-21'}, 'ops:L008EP': {'@desc': 'Legal Event Code 1', '#text': 'AK'}, 'ops:L018EP': {'@desc': 'DATE last exchanged', '#text': '2022-12-24'}, 'ops:L019EP': {'@desc': 'DATE first created', '#text': '2022-12-21'}, 'ops:L500EP': {'ops:L506EP': {'@desc': 'Kind Code of Ref Document', '#text': 'A1'}, 'ops:L507EP': {'@desc': 'Designated State(s)', '#text': 'AL AT BE BG CH CY CZ DE DK EE ES FI FR GB GR HR HU IE IS IT LI LT LU LV MC MK MT NL NO PL PT RO RS SE SI SK SM TR'}}}, {'@code': 'PUAI', '@desc': 'PUBLIC REFERENCE MADE UNDER ARTICLE 153(3) EPC TO A PUBLISHED INTERNATIONAL APPLICATION THAT HAS ENTERED THE EUROPEAN PHASE', '@infl': ' ', '@dateMigr': '00010101', 'ops:pre': {'@line': '00001', '#text': 'EP 22179301A 2022-11-18PUAI PUBLIC REFERENCE MADE UNDER ARTICLE 153(3) EPC TO A PUBLISHED INTERNATIONAL APPLICATION THAT HAS ENTERED THE EUROPEAN PHASE Free Format Text ORIGINAL CODE: 0009012'}, 'ops:L001EP': {'@desc': 'Country Code', '#text': 'EP'}, 'ops:L002EP': {'@desc': 'Filing / Published Document', '#text': 'F'}, 'ops:L003EP': {'@desc': 'Document Number', '#text': '22179301'}, 'ops:L004EP': {'@desc': 'Kind Code', '#text': 'A'}, 'ops:L005EP': {'@desc': 'IPR Type',...",docdb,EP,4106326,A1
1,false,2,82067485,"{'document-id': [{'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '4106326', 'kind': 'A1', 'date': '20221221'}, {'@document-id-type': 'epodoc', 'doc-number': 'EP4106326', 'date': '20221221'}]}","{'@doc-id': '574299984', '@is-representative': 'YES', 'document-id': {'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '22179301', 'kind': 'A', 'date': '20220615'}}","[{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202163202527', 'kind': 'P', 'date': '20210615'}, 'priority-active-indicator': 'YES'}]",docdb,EP,22179301,A,true,2,"{'document-id': [{'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '2022400244', 'kind': 'A1', 'date': '20221215'}, {'@document-id-type': 'epodoc', 'doc-number': 'US2022400244', 'date': '20221215'}]}","{'@doc-id': '584535325', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}}","[{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202163202527', 'kind': 'P', 'date': '20210615'}, 'priority-active-indicator': 'YES'}]","[{'@code': 'AS ', '@desc': 'ASSIGNMENT', '@infl': ' ', '@dateMigr': '00010101', 'ops:pre': [{'@line': '00001', '#text': 'US202217806216A 2022-06-27AS ASSIGNMENT OWNER PLANTRONICS, INC., CALIFORNIA'}, {'@line': '00002', '#text': 'US202217806216A 2022-06-27AS ASSIGNMENT Free Format Text ASSIGNMENT OF ASSIGNORS INTEREST;ASSIGNORS:SCHAEFER, STEPHEN PAUL;CHILDRESS, ROMMEL GABRIEL, JR;SIGNING DATES FROM 20220608 TO 20220609;REEL/FRAME:060322/0909'}], 'ops:L001EP': {'@desc': 'Country Code', '#text': 'US'}, 'ops:L002EP': {'@desc': 'Filing / Published Document', '#text': 'F'}, 'ops:L003EP': {'@desc': 'Document Number', '#text': '202217806216'}, 'ops:L004EP': {'@desc': 'Kind Code', '#text': 'A'}, 'ops:L005EP': {'@desc': 'IPR Type', '#text': 'PI'}, 'ops:L007EP': {'@desc': 'Gazette DATE', '#text': '2022-06-27'}, 'ops:L008EP': {'@desc': 'Legal Event Code 1', '#text': 'AS'}, 'ops:L018EP': {'@desc': 'DATE last exchanged', '#text': '2022-12-24'}, 'ops:L019EP': {'@desc': 'DATE first created', '#text': '2022-12-21'}, 'ops:L500EP': {'ops:L509EP': {'@desc': 'OWNER', '#text': 'PLANTRONICS, INC., CALIFORNIA'}, 'ops:L510EP': {'@desc': 'Free Format Text', '#text': 'ASSIGNMENT OF ASSIGNORS INTEREST;ASSIGNORS:SCHAEFER, STEPHEN PAUL;CHILDRESS, ROMMEL GABRIEL, JR;SIGNING DATES FROM 20220608 TO 20220609;REEL/FRAME:060322/0909'}}}, {'@code': 'STPP', '@desc': 'INFORMATION ON STATUS: PATENT APPLICATION AND GRANTING PROCEDURE IN GENERAL', '@infl': ' ', '@dateMigr': '00010101', 'ops:pre': {'@line': '00001', '#text': 'US202217806216A 2022-07-18STPP INFORMATION ON STATUS: PATENT APPLICATION AND GRANTING PROCEDURE IN GENERAL Free Format Text DOCKETED NEW CASE - READY FOR EXAMINATION'}, 'ops:L001EP': {'@desc': 'Country Code', '#text': 'US'}, 'ops:L002EP': {'@desc': 'Filing / Published Document', '#text': 'F'}, 'ops:L003EP': {'@desc': 'Document Number', '#text': '202217806216'}, 'ops:L004EP': {'@desc': 'Kind Code', '#text': 'A'}, 'ops:L005EP': {'@desc': 'IPR Type', '#text': 'PI'}, 'ops:L007EP...",docdb,EP,4106326,A1
2,false,2,82067485,"{'document-id': [{'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '2022400244', 'kind': 'A1', 'date': '20221215'}, {'@document-id-type': 'epodoc', 'doc-number': 'US2022400244', 'date': '20221215'}]}","{'@doc-id': '584535325', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}}","[{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202163202527', 'kind': 'P', 'date': '20210615'}, 'priority-active-indicator': 'YES'}]",docdb,EP,22179301,A,true,2,"{'document-id': [{'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '4106326', 'kind': 'A1', 'date': '20221221'}, {'@document-id-type': 'epodoc', 'doc-number': 'EP4106326', 'date': '20221221'}]}","{'@doc-id': '574299984', '@is-representative': 'YES', 'document-id': {'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '22179301', 'kind': 'A', 'date': '20220615'}}","[{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202163202527', 'kind': 'P', 'date': '20210615'}, 'priority-active-indicator': 'YES'}]","[{'@code': 'AK ', '@desc': 'DESIGNATED CONTRACTING STATES', '@infl': '+', '@dateMigr': '00010101', 'ops:pre': [{'@line': '00001', '#text': 'EP 22179301A 2022-12-21AK +DESIGNATED CONTRACTING STATES Kind Code of Ref Document A1'}, {'@line': '00002', '#text': 'EP 22179301A 2022-12-21AK +DESIGNATED CONTRACTING STATES Designated State(s) AL AT BE BG CH CY CZ DE DK EE ES FI FR GB GR HR HU IE IS IT LI LT LU LV MC MK MT NL NO PL PT RO RS SE SI SK SM TR'}], 'ops:L001EP': {'@desc': 'Country Code', '#text': 'EP'}, 'ops:L002EP': {'@desc': 'Filing / Published Document', '#text': 'F'}, 'ops:L003EP': {'@desc': 'Document Number', '#text': '22179301'}, 'ops:L004EP': {'@desc': 'Kind Code', '#text': 'A'}, 'ops:L005EP': {'@desc': 'IPR Type', '#text': 'PI'}, 'ops:L007EP': {'@desc': 'Gazette DATE', '#text': '2022-12-21'}, 'ops:L008EP': {'@desc': 'Legal Event Code 1', '#text': 'AK'}, 'ops:L018EP': {'@desc': 'DATE last exchanged', '#text': '2022-12-24'}, 'ops:L019EP': {'@desc': 'DATE first created', '#text': '2022-12-21'}, 'ops:L500EP': {'ops:L506EP': {'@desc': 'Kind Code of Ref Document', '#text': 'A1'}, 'ops:L507EP': {'@desc': 'Designated State(s)', '#text': 'AL AT BE BG CH CY CZ DE DK EE ES FI FR GB GR HR HU IE IS IT LI LT LU LV MC MK MT NL NO PL PT RO RS SE SI SK SM TR'}}}, {'@code': 'PUAI', '@desc': 'PUBLIC REFERENCE MADE UNDER ARTICLE 153(3) EPC TO A PUBLISHED INTERNATIONAL APPLICATION THAT HAS ENTERED THE EUROPEAN PHASE', '@infl': ' ', '@dateMigr': '00010101', 'ops:pre': {'@line': '00001', '#text': 'EP 22179301A 2022-11-18PUAI PUBLIC REFERENCE MADE UNDER ARTICLE 153(3) EPC TO A PUBLISHED INTERNATIONAL APPLICATION THAT HAS ENTERED THE EUROPEAN PHASE Free Format Text ORIGINAL CODE: 0009012'}, 'ops:L001EP': {'@desc': 'Country Code', '#text': 'EP'}, 'ops:L002EP': {'@desc': 'Filing / Published Document', '#text': 'F'}, 'ops:L003EP': {'@desc': 'Document Number', '#text': '22179301'}, 'ops:L004EP': {'@desc': 'Kind Code', '#text': 'A'}, 'ops:L005EP': {'@desc': 'IPR Type',...",docdb,EP,4106326,A1
3,false,2,82067485,"{'document-id': [{'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '2022400244', 'kind': 'A1', 'date': '20221215'}, {'@document-id-type': 'epodoc', 'doc-number': 'US2022400244', 'date': '20221215'}]}","{'@doc-id': '584535325', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}}","[{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202163202527', 'kind': 'P', 'date': '20210615'}, 'priority-active-indicator': 'YES'}]",docdb,EP,22179301,A,true,2,"{'document-id': [{'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '2022400244', 'kind': 'A1', 'date': '20221215'}, {'@document-id-type': 'epodoc', 'doc-number': 'US2022400244', 'date': '20221215'}]}","{'@doc-id': '584535325', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}}","[{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202163202527', 'kind': 'P', 'date': '20210615'}, 'priority-active-indicator': 'YES'}]","[{'@code': 'AS ', '@desc': 'ASSIGNMENT', '@infl': ' ', '@dateMigr': '00010101', 'ops:pre': [{'@line': '00001', '#text': 'US202217806216A 2022-06-27AS ASSIGNMENT OWNER PLANTRONICS, INC., CALIFORNIA'}, {'@line': '00002', '#text': 'US202217806216A 2022-06-27AS ASSIGNMENT Free Format Text ASSIGNMENT OF ASSIGNORS INTEREST;ASSIGNORS:SCHAEFER, STEPHEN PAUL;CHILDRESS, ROMMEL GABRIEL, JR;SIGNING DATES FROM 20220608 TO 20220609;REEL/FRAME:060322/0909'}], 'ops:L001EP': {'@desc': 'Country Code', '#text': 'US'}, 'ops:L002EP': {'@desc': 'Filing / Published Document', '#text': 'F'}, 'ops:L003EP': {'@desc': 'Document Number', '#text': '202217806216'}, 'ops:L004EP': {'@desc': 'Kind Code', '#text': 'A'}, 'ops:L005EP': {'@desc': 'IPR Type', '#text': 'PI'}, 'ops:L007EP': {'@desc': 'Gazette DATE', '#text': '2022-06-27'}, 'ops:L008EP': {'@desc': 'Legal Event Code 1', '#text': 'AS'}, 'ops:L018EP': {'@desc': 'DATE last exchanged', '#text': '2022-12-24'}, 'ops:L019EP': {'@desc': 'DATE first created', '#text': '2022-12-21'}, 'ops:L500EP': {'ops:L509EP': {'@desc': 'OWNER', '#text': 'PLANTRONICS, INC., CALIFORNIA'}, 'ops:L510EP': {'@desc': 'Free Format Text', '#text': 'ASSIGNMENT OF ASSIGNORS INTEREST;ASSIGNORS:SCHAEFER, STEPHEN PAUL;CHILDRESS, ROMMEL GABRIEL, JR;SIGNING DATES FROM 20220608 TO 20220609;REEL/FRAME:060322/0909'}}}, {'@code': 'STPP', '@desc': 'INFORMATION ON STATUS: PATENT APPLICATION AND GRANTING PROCEDURE IN GENERAL', '@infl': ' ', '@dateMigr': '00010101', 'ops:pre': {'@line': '00001', '#text': 'US202217806216A 2022-07-18STPP INFORMATION ON STATUS: PATENT APPLICATION AND GRANTING PROCEDURE IN GENERAL Free Format Text DOCKETED NEW CASE - READY FOR EXAMINATION'}, 'ops:L001EP': {'@desc': 'Country Code', '#text': 'US'}, 'ops:L002EP': {'@desc': 'Filing / Published Document', '#text': 'F'}, 'ops:L003EP': {'@desc': 'Document Number', '#text': '202217806216'}, 'ops:L004EP': {'@desc': 'Kind Code', '#text': 'A'}, 'ops:L005EP': {'@desc': 'IPR Type', '#text': 'PI'}, 'ops:L007EP...",docdb,EP,4106326,A1

#### 7.2.3.3 If ```ops:family-member|ops:legal``` contains JSON-like data structures, you might iterate through the rows to access specific fields within each legal detail:
* Define the function to process and combine data to a DataFrame named combined_df
* This example assumes ```ops:family-member|ops:legal``` contains a list of dictionaries with @code and @desc attributes.

In [8]:
import pandas as pd

# Function to process and combine data from the DataFrame
def process_family_data(family_df, num_rows=5):
    combined_data = []
    
    for index, row in family_df.head(num_rows).iterrows():
        # Initialize a dictionary to store combined data for the current row
        row_data = {
            'Family ID': row.get('ops:family-member|family-id', 'Unknown'),
            'Application Reference': row.get('ops:family-member|application-reference', 'Unknown'),
            'Priority Claim': row.get('ops:family-member|priority-claim', 'Unknown'),
        }
        
        # Extract and process nested document-id data
        pub_reference = row.get('ops:family-member|publication-reference', {})
        
        if isinstance(pub_reference, dict) and 'document-id' in pub_reference:
            document_ids = pub_reference['document-id']            
            if isinstance(document_ids, list):
                for doc_id in document_ids:
                    combined_row = row_data.copy()  # Copy base row_data to avoid modifying it
                    combined_row.update({
                        'Document ID Type': doc_id.get('@document-id-type', 'Unknown'),
                        'Country': doc_id.get('country', 'Unknown'),
                        'Document Number': doc_id.get('doc-number', 'Unknown'),
                        'Kind': doc_id.get('kind', 'Unknown'),
                    })
                    combined_data.append(combined_row)  # Append the combined row data to the list
            else:
                combined_data.append(row_data)  # Append if no document-id list
        else:
            combined_data.append(row_data)  # Append if no document-id data
    
    # Extract and add legal information
    for item in family_df['ops:family-member|ops:legal']:
        if isinstance(item, list):
            for legal_item in item:
                legal_code = legal_item.get('@code', 'Unknown')
                legal_description = legal_item.get('@desc', 'Unknown')
                # Add legal information to combined data
                for data in combined_data:
                    data.update({
                        'Legal Code': legal_code,
                        'Legal Description': legal_description
                    })
    
    # Convert the combined data into a DataFrame
    combined_df = pd.DataFrame(combined_data)
    
    return combined_df

#### 7.2.3.4 Print the columns of the DataFrame to verify the presence of the target column

In [9]:
# Print the columns of the DataFrame to verify the presence of the target column
print("DataFrame Columns:", family.columns)

# Example usage
combined_df = process_family_data(family)
print(combined_df)

DataFrame Columns: Index(['legal', 'total-result-count', 'ops:family-member|family-id',
       'ops:family-member|publication-reference',
       'ops:family-member|application-reference',
       'ops:family-member|priority-claim', 'ops:family-member|ops:legal',
       'ops:family-member|exchange-document',
       'ops:application-reference|document-id|document-id-type',
       'ops:application-reference|document-id|country',
       'ops:application-reference|document-id|doc-number',
       'ops:application-reference|document-id|kind'],
      dtype='object')
  Family ID  \
0  82067485
1  82067485
2  82067485
3  82067485

                                                                                                                                                              Application Reference  \
0  {'@doc-id': '574299984', '@is-representative': 'YES', 'document-id': {'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '22179301', 'kind': 'A', 'date': '20220615'}}
1  {'@doc-id': '574299984', '@is-representative': 'YES', 'document-id': {'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '22179301', 'kind': 'A', 'date': '20220615'}}
2                           {'@doc-id': '584535325', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}}
3                           {'@doc-id': '584535325', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}}

                                                                                                                                                                                                                                                                                                                                                                                                             Priority Claim  \
0  [{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202163202527', 'kind': 'P', 'date': '20210615'}, 'priority-active-indicator': 'YES'}]
1  [{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202163202527', 'kind': 'P', 'date': '20210615'}, 'priority-active-indicator': 'YES'}]
2  [{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202163202527', 'kind': 'P', 'date': '20210615'}, 'priority-active-indicator': 'YES'}]
3  [{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202217806216', 'kind': 'A', 'date': '20220609'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202163202527', 'kind': 'P', 'date': '20210615'}, 'priority-active-indicator': 'YES'}]

  Document ID Type  Country Document Number     Kind Legal Code  \
0            docdb       EP         4106326       A1       STCB
1           epodoc  Unknown       EP4106326  Unknown       STCB
2            docdb       US      2022400244       A1       STCB
3           epodoc  Unknown    US2022400244  Unknown       STCB

                                    Legal Description
0  INFORMATION ON STATUS: APPLICATION DISCONTINUATION
1  INFORMATION ON STATUS: APPLICATION DISCONTINUATION
2  INFORMATION ON STATUS: APPLICATION DISCONTINUATION
3  INFORMATION ON STATUS: APPLICATION DISCONTINUATION

In [10]:
import pandas as pd
from collections import Counter

# Fetch bibliographic data for published patent application
family_data = client.family(
    reference_type="application",  # publication, application, priority
    input=models.Docdb("09164213", "EP", "A"),  # original, docdb, epodoc
    constituents=None,
    output_type="Dataframe"  # optional, xml or DataFrame format
)
# display(family_data)

# Check if data is retrieved
if family_data.empty:
    print("No family data found for this publication number.")
else:
    # Extract relevant columns
    family_df = family_data[[        
        "ops:family-member|family-id",
        "ops:family-member|publication-reference",
        "ops:family-member|priority-claim"
    ]]

    # Rename columns for readability
    family_df.columns = [
        "Family ID",
        "Publication Reference",
        "Priority Claim"
    ]

    # Extract country codes from 'Publication Reference'
    country_codes = []
    for pub_ref in family_df["Publication Reference"]:
        if isinstance(pub_ref, dict) and "document-id" in pub_ref:
            for doc in pub_ref["document-id"]:
                if "@document-id-type" in doc and doc["@document-id-type"] == "docdb":
                    country_codes.append(doc.get("country", "Unknown"))

    # Generate statistics on country occurrences
    country_counts = Counter(country_codes)
    country_stats_df = pd.DataFrame(country_counts.items(), columns=["Country", "Count"]).sort_values(by="Count", ascending=False)

    # Add total sum row
    total_count = country_stats_df["Count"].sum()
    total_row = pd.DataFrame([["Total", total_count]], columns=["Country", "Count"])
    country_stats_df = pd.concat([country_stats_df, total_row], ignore_index=True)
    
    # Display the structured DataFrame and statistics
    display(family_df)
    print("\nFamily Member Country Statistics:")
    display(country_stats_df)

,Family ID,Publication Reference,Priority Claim
0,27290872,"{'document-id': [{'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '2101496', 'kind': 'A2', 'date': '20090916'}, {'@document-id-type': 'epodoc', 'doc-number': 'EP2101496', 'date': '20090916'}]}","[{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '32377096', 'kind': 'A', 'date': '19961204'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '34728496', 'kind': 'A', 'date': '19961226'}, 'priority-active-indicator': 'YES'}, {'@sequence': '3', '@kind': 'regional', 'document-id': {'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '06011611', 'kind': 'A', 'date': '19970228'}, 'priority-active-indicator': 'NO', 'priority-linkage-type': '3'}, {'@sequence': '4', '@kind': 'regional', 'document-id': {'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '97903634', 'kind': 'A', 'date': '19970228'}, 'priority-active-indicator': 'NO', 'priority-linkage-type': '3'}, {'@sequence': '5', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '4158396', 'kind': 'A', 'date': '19960228'}, 'priority-active-indicator': 'YES'}]"
1,27290872,"{'document-id': [{'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '2101496', 'kind': 'A3', 'date': '20091104'}, {'@document-id-type': 'epodoc', 'doc-number': 'EP2101496', 'date': '20091104'}]}","[{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '32377096', 'kind': 'A', 'date': '19961204'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '34728496', 'kind': 'A', 'date': '19961226'}, 'priority-active-indicator': 'YES'}, {'@sequence': '3', '@kind': 'regional', 'document-id': {'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '06011611', 'kind': 'A', 'date': '19970228'}, 'priority-active-indicator': 'NO', 'priority-linkage-type': '3'}, {'@sequence': '4', '@kind': 'regional', 'document-id': {'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '97903634', 'kind': 'A', 'date': '19970228'}, 'priority-active-indicator': 'NO', 'priority-linkage-type': '3'}, {'@sequence': '5', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '4158396', 'kind': 'A', 'date': '19960228'}, 'priority-active-indicator': 'YES'}]"
2,27290872,"{'document-id': [{'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '2101496', 'kind': 'B1', 'date': '20130123'}, {'@document-id-type': 'epodoc', 'doc-number': 'EP2101496', 'date': '20130123'}]}","[{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '32377096', 'kind': 'A', 'date': '19961204'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '34728496', 'kind': 'A', 'date': '19961226'}, 'priority-active-indicator': 'YES'}, {'@sequence': '3', '@kind': 'regional', 'document-id': {'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '06011611', 'kind': 'A', 'date': '19970228'}, 'priority-active-indicator': 'NO', 'priority-linkage-type': '3'}, {'@sequence': '4', '@kind': 'regional', 'document-id': {'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '97903634', 'kind': 'A', 'date': '19970228'}, 'priority-active-indicator': 'NO', 'priority-linkage-type': '3'}, {'@sequence': '5', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '4158396', 'kind': 'A', 'date': '19960228'}, 'priority-active-indicator': 'YES'}]"
3,27477573,"{'document-id': [{'@document-id-type': 'docdb', 'country': 'CA', 'doc-number': '2273891', 'kind': 'A1', 'date': '19980611'}, {'@document-id-type': 'epodoc', 'doc-number': 'CA2273891', 'date': '19980611'}]}","[{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '32377096', 'kind': 'A', 'date': '19961204'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '34728496', 'kind': 'A', 'date': '19961226'}, 'priority-active-indicator': 'YES'}, {'@sequence': '3', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '28809997', 'kind': 'A', 'date': '19971021'}, 'priority-active-indicator': 'YES'}, {'@sequence': '4', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '23432097', 'kind': 'A', 'date': '19970829'}, 'priority-active-indicator': 'YES'}, {'@sequence': '5', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '9700615', 'kind': 'W', 'date': '19970228'}, 'priority-active-indicator': 'NO', 'priority-linkage-type': 'A'}, {'@sequence': '6', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '9704429', 'kind': 'W', 'date': '19971203'}, 'priority-active-indicator': 'NO', 'priority-linkage-type': 'W'}]"
4,27477573,"{'document-id': [{'@document-id-type': 'docdb', 'country': 'CA', 'doc-number': '2273891', 'kind': 'C', 'date': '20010612'}, {'@document-id-type': 'epodoc', 'doc-number': 'CA2273891', 'date': '20010612'}]}","[{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '32377096', 'kind': 'A', 'date': '19961204'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '34728496', 'kind': 'A', 'date': '19961226'}, 'priority-active-indicator': 'YES'}, {'@sequence': '3', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '28809997', 'kind': 'A', 'date': '19971021'}, 'priority-active-indicator': 'YES'}, {'@sequence': '4', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '23432097', 'kind': 'A', 'date': '19970829'}, 'priority-active-indicator': 'YES'}, {'@sequence': '5', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '9700615', 'kind': 'W', 'date': '19970228'}, 'priority-active-indicator': 'NO', 'priority-linkage-type': 'A'}, {'@sequence': '6', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '9704429', 'kind': 'W', 'date': '19971203'}, 'priority-active-indicator': 'NO', 'priority-linkage-type': 'W'}]"
...,...,...,...
343,26531497,"{'document-id': [{'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '6925250', 'kind': 'B1', 'date': '20050802'}, {'@document-id-type': 'epodoc', 'doc-number': 'US6925250', 'date': '20050802'}]}","[{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '9803873', 'kind': 'W', 'date': '19980831'}, 'priority-active-indicator': 'NO', 'priority-linkage-type': 'W'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '23432097', 'kind': 'A', 'date': '19970829'}, 'priority-active-indicator': 'YES'}, {'@sequence': '3', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '33454397', 'kind': 'A', 'date': '19971204'}, 'priority-active-indicator': 'YES'}]"
344,26381225,"{'document-id': [{'@document-id-type': 'docdb', 'country': 'WO', 'doc-number': '9713364', 'kind': 'A1', 'date': '19970410'}, {'@document-id-type': 'epodoc', 'doc-number': 'WO9713364', 'date': '19970410'}]}","[{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '4158396', 'kind': 'A', 'date': '19960228'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '27671095', 'kind': 'A', 'date': '19950929'}, 'priority-active-indicator': 'YES'}]"
345,27290872,"{'document-id': [{'@document-id-type': 'docdb', 'country': 'WO', 'doc-number': '9732437', 'kind': 'A1', 'date': '19970904'}, {'@document-id-type': 'epodoc', 'doc-number': 'WO9732437', 'date': '19970904'}]}","[{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '32377096', 'kind': 'A', 'date': '19961204'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '34728496', 'kind': 'A', 'date': '19961226'}, 'priority-active-indicator': 'YES'}, {'@sequence': '3', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '4158396', 'kind': 'A', 'date': '19960228'}, 'priority-active-indicator': 'YES'}]"
346,27477573,"{'document-id': [{'@document-id-type': 'docdb', 'country': 'WO', 'doc-number': '9825413', 'kind': 'A1', 'date': '19980611'}, {'@document-id-type': 'epodoc', 'doc-number': 'WO9825413', 'date': '19980611'}]}","[{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '32377096', 'kind': 'A', 'date': '19961204'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '34728496', 'kind': 'A', 'date': '19961226'}, 'priority-active-indicator': 'YES'}, {'@sequence': '3', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '28809997', 'kind': 'A', 'date': '19971021'}, 'priority-active-indicator': 'YES'}, {'@sequence': '4', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '23432097', 'kind': 'A', 'date': '19970829'}, 'priority-active-indicator': 'YES'}, {'@sequence': '5', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '9700615', 'kind': 'W', 'date': '19970228'}, 'priority-active-indicator': 'NO'}]"
347,26531497,"{'document-id': [{'@document-id-type': 'docdb', 'country': 'WO', 'doc-number': '9912348', 'kind': 'A1', 'date': '19990311'}, {'@document-id-type': 'epodoc', 'doc-number': 'WO9912348', 'date': '19990311'}]}","[{'@sequence': '1', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '23432097', 'kind': 'A', 'date': '19970829'}, 'priority-active-indicator': 'YES'}, {'@sequence': '2', '@kind': 'national', 'document-id': {'@document-id-type': 'docdb', 'country': 'JP', 'doc-number': '33454397', 'kind': 'A', 'date': '19971204'}, 'priority-active-indicator': 'YES'}]"

Family Member Country Statistics:

   Country  Count
0       JP    135
1       US     82
2       EP     74
3       CN     20
4       DE     10
5       KR      8
6       HK      6
7       CA      4
8       WO      4
9       SG      2
10      MX      1
11      MY      1
12      TW      1
13   Total    348