#### Initialize the libraries, the environment and the client

In [1]:
import pandas as pd
import os
from pprint import pprint

try:
    from epo.tipdata.ops import OPSClient, models, exceptions
except ImportError:
    os.system('pip install epo-tipdata-ops')
    from epo.tipdata.ops import OPSClient, models, exceptions

%load_ext dotenv
%dotenv
%load_ext autoreload
%autoreload 2
    
client = OPSClient(
    key=os.getenv("OPS_KEY"), secret=os.getenv("OPS_SECRET")
)

## 7. **Available Methods and Examples of Use**
The OPSClient class offers a rich set of methods for retrieving patent data, enabling you to fetch specific details or conduct comprehensive searches. Examples have to be run in TIP.


### 7.1 Published_data Method
#### 7.1.1 published_data(reference_type, input, endpoint, constituents, output_type)
* Retrieves published patent data (bibliographic data, abstracts, etc.) for a specific document.
* Parameters:<br>
```reference_type (str)```: Type of patent reference (e.g., "publication", "application", or "priority")<br>
```input (Epodoc or Docdb)```: Patent document identifier<br>
(détailler input pour montrer le no de brevet à entrer dans son format particulier pour que le service puisse identifier le document
expliquer le sens de Epodoc par rapport à DocDb por avoir des formats différents des brevets à chercher)
```endpoint (str, optional)```: Specifies the data to retrieve (e.g., "biblio" for bibliographic data, "abstract" for abstracts) - defaults to "biblio"<br>
```constituents (list[str], optional)```: List of additional elements to retrieve with bibliographic data (e.g., images)<br>
```output_type (str)```: Format of the returned data (raw XML or Pandas DataFrame)<br>
#### 7.1.2 Easy help by instruction
Typing a '?' sticking to a command, like this here client.published_data```?``` and running it in a cell triggers a supportive information detailing the parameters of the command in use:

In [2]:
client.published_data?

Signature:
client.published_data(
    reference_type: Literal['publication', 'application', 'priority'],
    input: epo_ops.models.Docdb | epo_ops.models.Epodoc,
    endpoint: str = 'biblio',
    constituents: list[str] | None = None,
    output_type: Literal['raw', 'dataframe'] = 'raw',
) -> str | pandas.core.frame.DataFrame
Docstring:
Retrieval service for published data.

Args:
    reference_type (str): Any of "publication", "application", or "priority".
    input (Epodoc or Docdb): The document number. Cannot be Original.
    endpoint (str, optional): "biblio", "abstract", "equivalents", "claims", "description",
                              "fulltext", "images". Defaults to "biblio".
    constituents (list[str], optional): List of "biblio", "abstract", "images", "full cycle".
    output_type (str, optional): "dataframe" or "raw" (xml). Defaults to "raw"

Returns:
    str | pd.DataFrame: an xml string or a Dataframe

Note:
1) only the endpoint "biblio" or "equivalents" use the constituents parameter.
2) the services images and fulltext require a two-step process: inquire, then retrieve:
   - published_data(..., endpoint='images',...) to retrieve the image path, then
   - image(path=...)
File:      ~/.local/lib/python3.11/site-packages/epo/tipdata/ops/client.py
Type:      method

#### 7.1.3 Easy help as you type an instruction

Further, the above definition might be shown in a popup menu by putting the cursor on the opening parenthesis of the command "client.published_data()" and typing Shift + Tab. You may try it in the following cell:

In [3]:
# client.published_data()

#### 7.1.4 Example of retrieving bibliographic data with published_data method
This example retrieves bibliographic data (endpoint="biblio") for a published patent application identified by its document number stored in the Docdb object.

In [4]:
biblio = client.published_data(                           # Retrieve bibliography data
    reference_type="publication",                         # publication, application, priority
    input=models.Docdb("4106326", "EP", "A1", date=None), # original, docdb, epodoc
    endpoint="biblio",                                    # optional, defaults to biblio in case of published_data
    constituents=[],                                      # optional, list of constituents
    output_type="Dataframe",                              # optional, xml or DataFrame format
)
display(biblio)

,system,family-id,country,doc-number,kind,bibliographic-data|publication-reference,bibliographic-data|classifications-ipcr,bibliographic-data|patent-classifications,bibliographic-data|application-reference,bibliographic-data|priority-claims,bibliographic-data|parties,bibliographic-data|invention-title,bibliographic-data|references-cited,abstract|lang,abstract|p
0,ops.epo.org,82067485,EP,4106326,A1,{'document-id': [{'@document-id-type': 'docdb'...,"{'classification-ipcr': {'@sequence': '1', 'te...","{'patent-classification': [{'@sequence': '1', ...","{'@doc-id': '574299984', 'document-id': [{'@do...","{'priority-claim': [{'@sequence': '1', '@kind'...",{'applicants': {'applicant': [{'@sequence': '1...,"[{'@lang': 'de', '#text': 'AUTOMATISCHES FRAMI...","{'citation': [{'@cited-phase': 'undefined', '@...",en,A videoconferencing system includes different ...

In [5]:
# Print the columns of the DataFrame to verify presence
print("DataFrame Columns:", biblio.columns)

DataFrame Columns: Index(['system', 'family-id', 'country', 'doc-number', 'kind',
       'bibliographic-data|publication-reference',
       'bibliographic-data|classifications-ipcr',
       'bibliographic-data|patent-classifications',
       'bibliographic-data|application-reference',
       'bibliographic-data|priority-claims', 'bibliographic-data|parties',
       'bibliographic-data|invention-title',
       'bibliographic-data|references-cited', 'abstract|lang', 'abstract|p'],
      dtype='object')

The above code imports the Docdb class from the OPSClient class. Then, it defines the document number for the patent application we are interested in. It creates a Docdb object with that number. Finally, it calls the published_data method with the following arguments:<br>
* ```reference_type```: Set to "application" as we're looking for an application.<br>
* ```input```: The my_docdb object containing the document number.<br>
* ```endpoint```: Set to "biblio" to retrieve bibliographic data.<br>
* ```output_type```: Set to "dataframe" to get the data as a Pandas DataFrame for easier manipulation.<br>
The published_data method then calls the appropriate service and process the response. It will use the internal _get_content method to convert the response to the desired format (DataFrame in this case).<br>
The last line prints the first few rows of the biblio DataFrame, which contains information like system, family-id, country, doc-number, kind, publication-reference, classifications-ipcr, patent-classifications, application-reference, priority-claims, invention-title, etc. for the patent application.<br>

#### We want to concatenate input_country, input_doc_info and input_kind reads on three columns of the dataframe

In [6]:
# Extract the relevant fields from the DataFrame
input_country = biblio["country"].iloc[0]
input_doc_info = biblio["doc-number"].iloc[0]
input_kind = biblio["kind"].iloc[0]

# We want to concatenate input_country, input_doc_info and input_kind sread on three columns of the dataframe
print(f"input_country: {input_country}, input_doc_info {input_doc_info} and input_kind {input_kind }")

input_country: EP, input_doc_info 4106326 and input_kind A1

In [7]:
# Print the input Epodoc number
print(f"And obtain the input document: {input_country}{input_doc_info}{input_kind}")

And obtain the input document: EP4106326A1

#### We then loop through each column in the biblio DataFrame and print the column name and its first row value so as to expand the data

In [8]:
# Loop through each column in the biblio DataFrame and print the column name and its first row value
for column in biblio.columns:
    print(f"Column: {column}")
    
    # Get the first row value of the column
    value = biblio[column].iloc[0]
    
    # Print the value for inspection
    print();print(f"Value: {value}\n"[:1000])

Column: system

Value: ops.epo.org

Column: family-id

Value: 82067485

Column: country

Value: EP

Column: doc-number

Value: 4106326

Column: kind

Value: A1

Column: bibliographic-data|publication-reference

Value: {'document-id': [{'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '4106326', 'kind': 'A1', 'date': '20221221'}, {'@document-id-type': 'epodoc', 'doc-number': 'EP4106326', 'date': '20221221'}]}

Column: bibliographic-data|classifications-ipcr

Value: {'classification-ipcr': {'@sequence': '1', 'text': 'H04N   7/    14            A I'}}

Column: bibliographic-data|patent-classifications

Value: {'patent-classification': [{'@sequence': '1', 'classification-scheme': {'@office': 'EP', '@scheme': 'CPCI'}, 'section': 'H', 'class': '04', 'subclass': 'N', 'main-group': '7', 'subgroup': '147', 'classification-value': 'I', 'generating-office': 'US'}, {'@sequence': '2', 'classification-scheme': {'@office': 'EP', '@scheme': 'CPCI'}, 'section': 'H', 'class': '04', 'subclass': 'N', 'main-group': '7', 'subgroup': '147', 'classification-value': 'I', 'generating-office': 'EP'}, {'@sequence': '3', 'classification-scheme': {'@office': 'EP', '@scheme': 'CPCI'}, 'section': 'H', 'class': '04', 'subclass': 'N', 'main-group': '7', 'subgroup': '15', 'classification-value': 'I', 'generating-office': 'US'}, {'@sequence': '4', 'classification-scheme': {'@office': 'EP', '@scheme': 'CPCI'}, 'section': 'H', 'class': '04', 'subclass': 'N', 'main-group': '13', 'subgroup': '204', 'classification-value': 'I', 'generating-office': 'US'}, {'@sequence': '5', 'classification-scheme': {'@office': 'EP', '@sc
Column: bibliographic-data|application-reference

Value: {'@doc-id': '574299984', 'document-id': [{'@document-id-type': 'docdb', 'country': 'EP', 'doc-number': '22179301', 'kind': 'A'}, {'@document-id-type': 'epodoc', 'doc-number': 'EP20220179301', 'date': '20220615'}, {'@document-id-type': 'original', 'doc-number': '22179301.1'}]}

Column: bibliographic-data|priority-claims

Value: {'priority-claim': [{'@sequence': '1', '@kind': 'national', 'document-id': [{'@document-id-type': 'epodoc', 'doc-number': 'US202163202527P', 'date': '20210615'}, {'@document-id-type': 'original', 'doc-number': '202163202527 P'}]}, {'@sequence': '2', '@kind': 'national', 'document-id': [{'@document-id-type': 'epodoc', 'doc-number': 'US202217806216', 'date': '20220609'}, {'@document-id-type': 'original', 'doc-number': '202217806216'}]}]}

Column: bibliographic-data|parties

Value: {'applicants': {'applicant': [{'@sequence': '1', '@data-format': 'epodoc', 'applicant-name': {'name': 'PLANTRONICS\u2002[US]'}}, {'@sequence': '1', '@data-format': 'original', 'applicant-name': {'name': 'Plantronics, Inc'}}]}, 'inventors': {'inventor': [{'@sequence': '1', '@data-format': 'epodoc', 'inventor-name': {'name': 'SCHAEFER STEPHEN PAUL\u2002[US]'}}, {'@sequence': '2', '@data-format': 'epodoc', 'inventor-name': {'name': 'CHILDRESS JR ROMMEL GABRIEL\u2002[US]'}}, {'@sequence': '1', '@data-format': 'original', 'inventor-name': {'name': 'SCHAEFER, Stephen Paul,'}}, {'@sequence': '2', '@data-format': 'original', 'inventor-name': {'name': 'CHILDRESS JR, Rommel Gabriel'}}]}}

Column: bibliographic-data|invention-title

Value: [{'@lang': 'de', '#text': 'AUTOMATISCHES FRAMING MIT MEHREREN KAMERAS'}, {'@lang': 'fr', '#text': 'CADRAGE AUTOMATIQUE À CAMÉRAS MULTIPLES'}, {'@lang': 'en', '#text': 'MULTI-CAMERA AUTOMATIC FRAMING'}]

Column: bibliographic-data|references-cited

Value: {'citation': [{'@cited-phase': 'undefined', '@cited-by': 'applicant', '@sequence': '1', 'patcit': {'@dnum-type': 'application number', '@num': '1', 'document-id': [{'@document-id-type': 'epodoc', 'doc-number': 'US202762632025P'}, {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '202762632025', 'kind': None}]}}, {'@cited-phase': 'undefined', '@cited-by': 'applicant', '@sequence': '2', 'patcit': {'@dnum-type': 'publication number', '@num': '2', 'document-id': [{'@document-id-type': 'epodoc', 'doc-number': 'US8395653', 'date': '20130312'}, {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '8395653', 'kind': 'B2', 'date': '20130312'}]}}, {'@cited-phase': 'undefined', '@cited-by': 'applicant', '@sequence': '3', 'patcit': {'@dnum-type': 'publication number', '@num': '3', 'document-id': [{'@document-id-type': 'epodoc', 'doc-number': 'US8842161', 'date': '20140923'}, {'@document-id-type': 'docdb', 'country': 'US', 'doc-number': '8842161', 'kind': 'B2', 'date': '
Column: abstract|lang

Value: en

Column: abstract|p

Value: A videoconferencing system includes different cameras with different fields-of-view (FOVs). Frames of images acquired by these cameras may be processed to determine states, such as number of users present, talking, and so forth. Based on these states, frames from one camera may be selected to send to a far site. If the two states indicate no change in camera source from a first time to a second time, the current frame from the first camera that is sent to the far site is followed by another frame from the same camera. If the two states indicate a change in camera source from the first time to the second time, the current frame from the first camera that is sent to the far site is followed by a frame from the different camera. Depending on the two states and the cameras used, different transition effects may be applied to improve presentation.

The above loop iterates over ```biblio.columns```, which contains the list of column names in the DataFrame.

For each column, it prints the column name and then retrieves the value in the first row with ```.iloc[0]```, printing the content to inspect the structure.

This approach allows us to expend all columns and their corresponding collapsed values in the first row.

#### 7.1.5 Continuation of the prior example to retrieve classification data from the bibliographic data
This continued example shows a manageable number of rows and displays a limited number of classification sequences, in a concise output within an adjustable limit to show more or fewer classifications per row as needed.

#### 7.1.5.1 extract_classifications Function and  Limit Option
* extract_classifications Function: This function now directly returns a list of concatenated classification strings instead of printing detailed classification information.
* Limit Option: The function allows limiting the number of classifications (set to 5 as in your original code).

In [9]:
# Function to extract classification information and return unique concatenated classifications
def extract_classifications(classification_info, limit=None):
    classifications = set()  # Use a set to store unique classifications
    
    # Check if the classification info contains patent classifications
    if isinstance(classification_info, dict) and 'patent-classification' in classification_info:
        class_list = classification_info['patent-classification']
        
        # Limit the number of classifications if specified
        if limit:
            class_list = class_list[:limit]
        
        # Extract relevant classification details
        for classification in class_list:
            section = classification.get('section', '')
            _class = classification.get('class', '')
            subclass = classification.get('subclass', '')
            main_group = classification.get('main-group', '')
            subgroup = classification.get('subgroup', '')
            
            # Concatenate classification string
            classification_str = f"{section}{_class}{subclass}{main_group}/{subgroup}"
            classifications.add(classification_str)  # Use a set to ensure uniqueness
    
    return list(classifications)  # Convert back to a list to maintain original return format

#### 7.1.5.2 Concatenating Classifications
* Concatenating Classifications: After collecting all classifications, the results are stored in a DataFrame and output at the end.

In [10]:
# List to store concatenated classifications for each row
all_classifications = []

# Iterate through the rows of the DataFrame
for index, row in biblio.iterrows():
    if 'bibliographic-data|patent-classifications' in biblio.columns:
        classification_info = row['bibliographic-data|patent-classifications']
        # Extract unique classifications (limited to first 5)
        classifications = extract_classifications(classification_info, limit=5)
        all_classifications.extend(classifications)

# Convert the list of classifications to a DataFrame (if needed)
classification_df = pd.DataFrame({'Classification': all_classifications})

# Output the concatenated classifications
print(classification_df['Classification'])

0    H04N23/695
1      H04N7/15
2     H04N7/147
3    H04N13/204
Name: Classification, dtype: object

### 7.1.6 Second continuation of the prior example to retrieve references cited from the bibliographic data
This continued example shows a manageable number of rows and displays a limited number of citations, in a concise output.

#### 7.1.6.1 Normalize_doc_number function
* Function to normalize document numbers by stripping leading non-numeric characters for comparison

In [11]:
import pandas as pd

# Function to normalize document numbers by stripping leading non-numeric characters for comparison
def normalize_doc_number(doc_number):
    if doc_number:
        return ''.join(filter(str.isdigit, doc_number))  # Retain only the numeric part
    return doc_number

# Compile all references into a DataFrame
references_data = []

# Iterate through each row in the DataFrame
for index, row in biblio.iterrows():
    if 'bibliographic-data|references-cited' in biblio.columns:
        references_info = row['bibliographic-data|references-cited']

        if isinstance(references_info, dict) and 'citation' in references_info:
            citations = references_info['citation']

            if isinstance(citations, list):
                for ref in citations:
                    # For patent citations
                    if 'patcit' in ref:
                        patcit = ref['patcit']
                        if 'document-id' in patcit:
                            for doc in patcit['document-id']:
                                reference_entry = {
                                    'Document Number': doc.get('doc-number', None),
                                    'Normalized Document Number': normalize_doc_number(doc.get('doc-number', None)),
                                    'Country': doc.get('country', None),
                                    'Kind': doc.get('kind', None),
                                    'Date': doc.get('date', None),
                                    'Citation Category': ref.get('@cited-phase', None),
                                    'NPL Citation': None  # Set NPL Citation to None for patent citations
                                }
                                references_data.append(reference_entry)

                    # For non-patent literature citations (NPL)
                    elif 'nplcit' in ref:
                        nplcit = ref['nplcit']
                        reference_entry = {
                            'Document Number': None,
                            'Normalized Document Number': None,
                            'Country': None,
                            'Kind': None,
                            'Date': None,
                            'Citation Category': ref.get('@cited-phase', None),
                            'NPL Citation': nplcit.get('text', None)
                        }
                        references_data.append(reference_entry)

Handling Patent Citations ```patcit```:

* The patcit key contains a list of document-id, where each entry has doc-number, country, kind, and date. These values are extracted and added to the reference_entry.

Handling Non-Patent Literature Citations ```nplcit```:

* The nplcit key contains text for the citation, so when it's present, we create an entry for it in the DataFrame with fields such as NPL Citation.

#### 7.1.6.2 Handle references dataframe
* Convert list of dictionaries to a DataFrame
* Remove duplicates by 'Normalized Document Number', keeping the first occurrence
* Filter out rows where all fields are NaN or "None" for essential fields
* Drop the 'Normalized Document Number' column as it was only used for filtering duplicates
* Return the final DataFrame

In [12]:
# Convert list of dictionaries to a DataFrame
references_df = pd.DataFrame(references_data)

# Remove duplicates by 'Normalized Document Number', keeping the first occurrence
# This removes the duplicate rows like JPH08307902 and H08307902 by comparing only numeric parts of doc numbers
filtered_references_df = references_df.drop_duplicates(subset=['Normalized Document Number'])

# Filter out rows where all fields are NaN or "None" for essential fields
filtered_references_df = filtered_references_df.dropna(subset=['Document Number', 'Country', 'Kind', 'Date', 'NPL Citation'], how='all')

# Drop the 'Normalized Document Number' column as it was only used for filtering duplicates
filtered_references_df = filtered_references_df.drop(columns=['Normalized Document Number'])

# Return the final DataFrame
filtered_references_df

,Document Number,Country,Kind,Date,Citation Category,NPL Citation
0,US202762632025P,None,None,None,undefined,None
2,US8395653,None,None,20130312,undefined,None
4,US8842161,None,None,20140923,undefined,None
6,US9030520,None,None,20150512,undefined,None
8,US9542603,None,None,20170110,undefined,None
10,US9723260,None,None,20170801,undefined,None
12,US9800835,None,None,20171024,undefined,None
14,US10091412,None,None,20181002,undefined,None
16,US10122972,None,None,20181106,undefined,None
18,US10187579,None,None,20190122,undefined,None
20,US10574899,None,None,20200225,undefined,None
22,WO2020103078,None,None,20200528,undefined,None
24,WO2020103068,None,None,20200528,undefined,None
26,US10778941,None,None,20200915,undefined,None
28,US2011285807,None,None,20111124,national-search-report,None
30,US2012320143,None,None,20121220,national-search-report,None
32,US9930270,None,None,20180327,national-search-report,None
34,US2020351435,None,None,20201105,national-search-report,None
36,US10904485,None,None,20210126,national-search-report,None
38,None,None,None,None,national-search-report,"- ABHISHEK RANJAN ET AL, ""Improving meeting ca..."

### 7.1.7 Example of retrieving a set of claims with the published_data method
This example retrieves claims (endpoint="claims") for a published patent application identified by its document number stored in the Docdb object. One can run each cell separatelyand see the intermediate results, which helps understanding the flow of the program.

#### 7.1.7.1 Retrieves claims of EP4106326A1
* published_data is called for retrieving a set of claims from an EP publication number

In [13]:
biblio = client.published_data(                           # Retrieve bibliography data
    reference_type="publication",                         # publication, application, priority
    input=models.Docdb("4106326", "EP", "%%", date=None), # original, docdb, epodoc
    endpoint='claims',                                    # "biblio", "abstract", "equivalents", "claims", "description", "fulltext", "images",                                    # optional, defaults to biblio in case of published_data
    constituents=[],                                      # optional, list of constituents from ['biblio', 'abstract', 'images', 'full cycle'], 
    output_type="raw",                                    # optional, xml or DataFrame format
)
pprint(biblio)

('<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" '
 'href="../../../../../style/pub-ftxt-claims.xsl"?>\n'
 '<ops:world-patent-data xmlns="http://www.epo.org/exchange" '
 'xmlns:ops="http://ops.epo.org" '
 'xmlns:xlink="http://www.w3.org/1999/xlink"><ftxt:fulltext-documents '
 'xmlns="http://www.epo.org/fulltext" '
 'xmlns:ftxt="http://www.epo.org/fulltext"><ftxt:fulltext-document '
 'system="ops.epo.org" '
 'fulltext-format="text-only"><bibliographic-data><publication-reference '
 'data-format="docdb"><document-id><country>EP</country><doc-number>4106326</doc-number><kind>A1</kind></document-id></publication-reference></bibliographic-data><claims '
 'lang="EN"><claim><claim-text>1. A system (100) comprising:\n'
 'a first camera (118, 120) with a first field-of-view, FOV, (420, 422);\n'
 'a second camera (120, 118) with a second FOV (420, 422);\n'
 'a memory (210) storing computer-executable instructions (210); and\n'
 'a hardware processor (206) coupled to (200) the first camera (118, 120) and '
 'the second camera (120, 118), and the hardware processor (206) configured to '
 'execute the computer-executable instructions (210) to:\n'
 'acquire at least a first frame (514) using the first camera (118, 120);\n'
 'determine a first state associated with the at least a first frame (515);\n'
 'acquire at least a second frame (516) using the second camera (120, 118);\n'
 'determine a second state associated with the at least a second frame (518);\n'
 'determine, based on the first state and the second state, change data '
 'indicative of a change in camera source from the first camera to the second '
 'camera (520);\n'
 'determine output data (526) comprising a dissolve transition (526) from the '
 'at least a first frame (514) to the at least a second frame (516); and\n'
 'send the output data (528).</claim-text><claim-text>2. The system (100) of '
 'claim 1, wherein:\n'
 'the first FOV (420, 422) incorporates the second FOV (420, '
 '422).</claim-text><claim-text>3. The system (100) of claim 1, wherein:\n'
 'the second FOV (420, 422) incorporates the first FOV (420, '
 '422).</claim-text><claim-text>4. The system (100) of claim 1, wherein the '
 'dissolve transition (526) comprises:\n'
 'overlap the at least a first frame (530) and the at least a second frame '
 '(536, 538) for a duration of time; and\n'
 'after the duration of time has elapsed, transition to the at least a second '
 'frame (536, 538).</claim-text><claim-text>5. The system (100) of claim 1, '
 'wherein the dissolve transition comprises:\n'
 'transition from the first frame (530) to a blank frame at a first time; and\n'
 'transition from the blank frame to the second frame (536, 538) at a second '
 'time.</claim-text><claim-text>6. The system (100) of claim 1, wherein:\n'
 'the first state comprises one or more of:\n'
 'no persons in a room (502),\n'
 'one or more persons in the room (606, 610, 614),\n'
 'one or more persons joining a group (702),\n'
 'one or more persons leaving the group (706),\n'
 'all persons leaving the group (708),\n'
 'one or more persons talking (712),\n'
 'one or more additional persons talking (802, 806), or\n'
 'one or more persons no longer talking (808, 812); and\n'
 'the second state comprises one or more of:\n'
 'no persons in a room (602),\n'
 'one or more persons in the room (606, 610, 614),\n'
 'one or more persons joining a group (702),\n'
 'one or more persons leaving the group (706),\n'
 'all persons leaving the group (708),\n'
 'one or more persons talking (712),\n'
 'one or more additional persons talking (802, 806), or\n'
 'one or more persons no longer talking (808, 812).</claim-text><claim-text>7. '
 'The system (100) of claim 1, wherein:\n'
 'the first state is indicative of a group of persons in a room (504); and\n'
 'the second state is indicative of one or more of the persons in the group '
 'talking (506).</claim-text><claim-text>8. The system (100) of claim 7, the '
 'hardware processor further configured to execute the computer-executable '
 'instructions to:\n'
 'acquire at least a third frame using the second camera (514 or 516);\n'
 'determine a third state associated with the at least a third frame (515 or '
 '518);\n'
 'determine the third state is indicative of two persons talking (1022);\n'
 'determine the two persons talking are more than a threshold pixel distance '
 'away from each other (1026);\n'
 'determine second output data comprising a split screen transition that adds '
 'the third frame next to the second frame (1028); and\n'
 'send the second output data (1028).</claim-text><claim-text>9. The system '
 '(100) of claim 1, wherein:\n'
 'the first state is indicative of one or more persons talking (506); and\n'
 'the second state is indicative of the one or more persons talking and one or '
 'more additional persons talking (508).</claim-text><claim-text>10. The '
 'system (100) of claim 1, wherein:\n'
 'the first state is indicative of two or more persons talking (508); and\n'
 'the second state is indicative of one person talking '
 '(510).</claim-text><claim-text>11. The system (100) of claim 1, wherein:\n'
 'the first state is indicative of at least one person talking (506); and\n'
 'the second state is indicative of no persons talking '
 '(504).</claim-text><claim-text>12. The system (100) of claim 1, further '
 'comprising:\n'
 'a third camera with a third FOV (420, 422); and\n'
 'the hardware processor further configured to execute the computer-executable '
 'instructions to:\n'
 'acquire at least a third frame using the third camera (514, 516);\n'
 'determine a third state associated with the at least a third frame (515, '
 '518);\n'
 'determine, based on the second state and the third state, second change data '
 '(520) indicative of a change in camera source from the second camera to the '
 'third camera;\n'
 'determine second output data comprising a second dissolve transition from '
 'the at least a second frame to the third frame (526); and\n'
 'send the second output data (528).</claim-text><claim-text>13. A method '
 'comprising:\n'
 'acquiring one or more first images (514), wherein the one or more first '
 'images are acquired using a first camera (118 or 120) or a second camera '
 '(120 or 118);\n'
 'determining a first state associated with the one or more first images '
 '(515);\n'
 'acquiring one or more second images (516), wherein the one or more second '
 'images are acquired using the first camera (118 or 120) or the second camera '
 '(120 or 118);\n'
 'determining a second state associated with the one or more second images '
 '(518);\n'
 'determining, based on the first state and the second state, change data '
 'indicative of whether a change in camera source is involved;\n'
 'if the change data is indicative of a change in camera source (522), '
 'generating first output data comprising a dissolve transition between the '
 'one or more first images and the one or more second images (526);\n'
 'if the change data is not indicative of a change in camera source (522), '
 'generating second output data comprising an ease transition between the one '
 'or more first images and the one or more second images (526); and\n'
 'sending the first output data or the second output data '
 '(528).</claim-text><claim-text>14. The method of claim 13, wherein the '
 'dissolve transition (526) comprises:\n'
 'overlapping the at least a first frame (530) and the at least a second frame '
 '(536, 538) for a duration of time; and\n'
 'after the duration of time has elapsed, transitioning to the at least a '
 'second frame (536, 538).</claim-text><claim-text>15. The method of claim 13, '
 'wherein the dissolve transition (526) comprises:\n'
 'transitioning from a first frame (530) to a blank frame at a first time; '
 'and\n'
 'transitioning from the blank frame to a second frame (536 or 538) at a '
 'second '
 'time.</claim-text></claim></claims></ftxt:fulltext-document></ftxt:fulltext-documents></ops:world-patent-data>')

#### 7.1.7.2 Import and Parse claims XML
* Parse the XML response
* Define namespaces correctly
* Find all claim-text elements under the correct namespace

In [14]:
import xml.etree.ElementTree as ET

# Parse the XML response
root = ET.fromstring(biblio)

# Define namespaces correctly
namespaces = {
    'ftxt': 'http://www.epo.org/fulltext',
    'ops': 'http://ops.epo.org',
    'default': 'http://www.epo.org/exchange',
}

# Find all claim-text elements under the correct namespace
claims = root.findall(".//ftxt:claim-text", namespaces)

print(f"Number of claims found: {len(claims)}")

Number of claims found: 15

#### 7.1.7.3 Function extract_claim_number
* Extract the leading claimn number from the claim text (e.g., "1." from "1. Optische Platte...")
* Convert to an integer if possible

In [15]:
def extract_claim_number(claim_text):
    # Extract the leading number from the claim text (e.g., "1." from "1. Optische Platte...")
    claim_leading_number = claim_text.strip().split()[0].rstrip(".")
    
    # Convert to an integer if possible
    try:
        return int(claim_leading_number)
    except ValueError:
        return None

#### 7.1.7.4 Process and print the claims
* Check if claims were found
* Format each claim text separately
* Print the claim text

In [16]:
# Check if claims were found and print them
if not claims:
    print("No claims found.")
else:
    expected_claim_number = 1  # Start from the first claim
    for claim in claims:
        claim_text = "".join(claim.itertext())  # Extract the text content from the claim element
        
        claim_number = extract_claim_number(claim_text)

        # If the claim number doesn't match the expected number, stop
        if claim_number != expected_claim_number:
            print(f"Claim mismatch detected. Expected Claim {expected_claim_number} but got Claim {claim_number}.")
            break

        # Print the claim text
        print(f"Claim {expected_claim_number}: {claim_text}\n")

        # Increment the expected claim number
        expected_claim_number += 1

Claim 1: 1. A system (100) comprising:
a first camera (118, 120) with a first field-of-view, FOV, (420, 422);
a second camera (120, 118) with a second FOV (420, 422);
a memory (210) storing computer-executable instructions (210); and
a hardware processor (206) coupled to (200) the first camera (118, 120) and the second camera (120, 118), and the hardware processor (206) configured to execute the computer-executable instructions (210) to:
acquire at least a first frame (514) using the first camera (118, 120);
determine a first state associated with the at least a first frame (515);
acquire at least a second frame (516) using the second camera (120, 118);
determine a second state associated with the at least a second frame (518);
determine, based on the first state and the second state, change data indicative of a change in camera source from the first camera to the second camera (520);
determine output data (526) comprising a dissolve transition (526) from the at least a first frame (514) to the at least a second frame (516); and
send the output data (528).

Claim 2: 2. The system (100) of claim 1, wherein:
the first FOV (420, 422) incorporates the second FOV (420, 422).

Claim 3: 3. The system (100) of claim 1, wherein:
the second FOV (420, 422) incorporates the first FOV (420, 422).

Claim 4: 4. The system (100) of claim 1, wherein the dissolve transition (526) comprises:
overlap the at least a first frame (530) and the at least a second frame (536, 538) for a duration of time; and
after the duration of time has elapsed, transition to the at least a second frame (536, 538).

Claim 5: 5. The system (100) of claim 1, wherein the dissolve transition comprises:
transition from the first frame (530) to a blank frame at a first time; and
transition from the blank frame to the second frame (536, 538) at a second time.

Claim 6: 6. The system (100) of claim 1, wherein:
the first state comprises one or more of:
no persons in a room (502),
one or more persons in the room (606, 610, 614),
one or more persons joining a group (702),
one or more persons leaving the group (706),
all persons leaving the group (708),
one or more persons talking (712),
one or more additional persons talking (802, 806), or
one or more persons no longer talking (808, 812); and
the second state comprises one or more of:
no persons in a room (602),
one or more persons in the room (606, 610, 614),
one or more persons joining a group (702),
one or more persons leaving the group (706),
all persons leaving the group (708),
one or more persons talking (712),
one or more additional persons talking (802, 806), or
one or more persons no longer talking (808, 812).

Claim 7: 7. The system (100) of claim 1, wherein:
the first state is indicative of a group of persons in a room (504); and
the second state is indicative of one or more of the persons in the group talking (506).

Claim 8: 8. The system (100) of claim 7, the hardware processor further configured to execute the computer-executable instructions to:
acquire at least a third frame using the second camera (514 or 516);
determine a third state associated with the at least a third frame (515 or 518);
determine the third state is indicative of two persons talking (1022);
determine the two persons talking are more than a threshold pixel distance away from each other (1026);
determine second output data comprising a split screen transition that adds the third frame next to the second frame (1028); and
send the second output data (1028).

Claim 9: 9. The system (100) of claim 1, wherein:
the first state is indicative of one or more persons talking (506); and
the second state is indicative of the one or more persons talking and one or more additional persons talking (508).

Claim 10: 10. The system (100) of claim 1, wherein:
the first state is indicative of two or more persons talking (508); and
the second state is indicative of one person talking (510).

Claim 11: 11. The system (100) of claim 1, wherein:
the first state is indicative of at least one person talking (506); and
the second state is indicative of no persons talking (504).

Claim 12: 12. The system (100) of claim 1, further comprising:
a third camera with a third FOV (420, 422); and
the hardware processor further configured to execute the computer-executable instructions to:
acquire at least a third frame using the third camera (514, 516);
determine a third state associated with the at least a third frame (515, 518);
determine, based on the second state and the third state, second change data (520) indicative of a change in camera source from the second camera to the third camera;
determine second output data comprising a second dissolve transition from the at least a second frame to the third frame (526); and
send the second output data (528).

Claim 13: 13. A method comprising:
acquiring one or more first images (514), wherein the one or more first images are acquired using a first camera (118 or 120) or a second camera (120 or 118);
determining a first state associated with the one or more first images (515);
acquiring one or more second images (516), wherein the one or more second images are acquired using the first camera (118 or 120) or the second camera (120 or 118);
determining a second state associated with the one or more second images (518);
determining, based on the first state and the second state, change data indicative of whether a change in camera source is involved;
if the change data is indicative of a change in camera source (522), generating first output data comprising a dissolve transition between the one or more first images and the one or more second images (526);
if the change data is not indicative of a change in camera source (522), generating second output data comprising an ease transition between the one or more first images and the one or more second images (526); and
sending the first output data or the second output data (528).

Claim 14: 14. The method of claim 13, wherein the dissolve transition (526) comprises:
overlapping the at least a first frame (530) and the at least a second frame (536, 538) for a duration of time; and
after the duration of time has elapsed, transitioning to the at least a second frame (536, 538).

Claim 15: 15. The method of claim 13, wherein the dissolve transition (526) comprises:
transitioning from a first frame (530) to a blank frame at a first time; and
transitioning from the blank frame to a second frame (536 or 538) at a second time.

### 7.1.8 Example of fetching description data
This example retrieves description data (endpoint="description") for a published patent identified by its document number stored in the Docdb object.

#### 7.1.8.1 Fetch description data for a publication
* The function published_data is called for retrieving the description from an EP publication number

In [26]:
# Fetch description for a publication
description = client.published_data(
        reference_type='publication', # application, publication
        input=models.Docdb("4106326", "EP", "A1", date=None),
        endpoint='description',
        constituents=[],
        output_type="raw"
    )
description

'<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="../../../../../style/pub-ftxt-description.xsl"?>\n<ops:world-patent-data xmlns="http://www.epo.org/exchange" xmlns:ops="http://ops.epo.org" xmlns:xlink="http://www.w3.org/1999/xlink"><ftxt:fulltext-documents xmlns="http://www.epo.org/fulltext" xmlns:ftxt="http://www.epo.org/fulltext"><ftxt:fulltext-document system="ops.epo.org" fulltext-format="text-only"><bibliographic-data><publication-reference data-format="docdb"><document-id><country>EP</country><doc-number>4106326</doc-number><kind>A1</kind></document-id></publication-reference></bibliographic-data><description lang="EN"><p>PRIORITY</p><p>[0001]    This application claims priority to,  U.S. Provisional Patent Application No. 63/202,527, filed on June 15, 2021 , entitled &quot;Telephoto and Wide-Angle Automatic Framing&quot;, which is hereby incorporated by reference in its entirety. </p><p>BACKGROUND</p><p>[0002]    In a videoconference, framing refers to the view or frame provided to the far end or site. Originally, framing was performed manually, first locally and then remotely. The pan, tilt, and zoom (PTZ) of the camera was manually controlled to provide a desired picture. Generally, the camera was set to show all participants present in the meeting room and not moved as people entered or left or different people spoke. An improvement over the manual system were systems that determined the talker and then automatically directed the camera to that talker. This would usually involve moving the camera, which was disorienting to viewers at the far end. In some cases, the last image before movement started was just displayed until movement was completed. In a further improvement, two cameras were used, one to frame all the participants or the whole room and one for talker focus. The transmitted image would change from the talker view to the room, or all participants view, when the talker changed so that a live view was always available, but camera motion was not shown. </p><p>[0003]    While these improvements provided a better experience than manual framing, they were still limited to all participants or a single talker. In practice, there are many more situations than these two, such as multiple talkers, and those situations were not handled smoothly. When those situations were occurring, the viewers at the far end had a less pleasant experience, as either some of the talkers were not shown or there were an excessive number of framing changes. </p><p>BRIEF DESCRIPTION OF FIGURES</p><p>[0004]    The detailed description is set forth with reference to the accompanying figures. In the figures, the left-most digit(s) of a reference number identifies the figure in which the reference number first appears. The use of the same reference numbers in different figures indicates similar or identical items or features. The figures are not necessarily drawn to scale, and in some figures, the proportions or other aspects may be exaggerated to facilitate comprehension of particular aspects.\nFIG. 1  is an illustration of a videoconferencing endpoint, according to some implementations.\nFIG. 2  is an illustration of aspects of the videoconferencing endpoint of  FIG. 1 , according to some implementations.\nFIG. 3  is a high-level flowchart of participant framing operations of a videoconferencing endpoint, according to some implementations.\nFIG. 4  is an illustration of a conference room, the fields of view of the wide-angle and telephoto cameras, and a number of participants to illustrate framing, according to some implementations.\nFIG. 5  is a state diagram of framing states and transitions, according to some implementations.\nFig. 5A  is a flowchart to determine transitions between frames, according to some implementations.\nFigs. 5B-5F  are illustrations of transitions between frames, according to some implementations.\nFIG. 6  is a state diagram illustrating transitions from the Empty Room state, according to some implementations.\nFIG. 7  is a state diagram illustrating transitions from the Group Framing state, according to some implementations.\nFIG. 8  is a state diagram illustrating transitions from the Any Talker state, according to some implementations.\nFIG. 9  is a state diagram illustrating transitions from the Conversation state, according to some implementations.\nFIG. 10  is a state diagram illustrating transitions from the Unambiguous Talker state, according to some implementations.\nFig. 10A  is a flowchart illustrating development of split screen framing, according to some implementations.\nFIG. 11  is a view of a conference room, with rule of thirds grids for each camera, according to some implementations.\nFIG. 12  is a view of the conference room of  FIG. 11  with four participants framed in Group Framing mode with the resulting rule of thirds grid, according to some implementations.\nFIG. 13  is a view of the conference room of  FIG. 11  and participants of  FIG. 12  with a single talker in Any Talker mode with the resulting rule of thirds grid, according to some implementations.\nFIG. 14  is a view of the conference room of  FIG. 11  and participants of  FIG. 12  with two talkers in Conversation mode with the resulting rule of thirds grid, according to some implementations.\nFIG. 15  is a view of the conference room of  FIG. 11  and participants of  FIG. 12  with three talkers in Conversation mode with the resulting rule of thirds grid, according to some implementations.\nFIG. 16  is a view of the conference room of  FIG. 11  and participants of  FIG. 12  with one talker in Unambiguous Talker mode with the resulting rule of thirds grid, according to some implementations.\nFIG. 17  is a view of the conference room of  FIG. 11  and participants of  FIG. 12  with two talkers in split screen mode with two rule of thirds grids, according to some implementations.\nFIG. 18  is a view of the conference room of  FIG. 11  and participants of  FIG. 12  which has changed from the two talkers of  FIG. 17  to three talkers and the resulting single rule of thirds grid, according to some implementations.</p><p>[0005]    While implementations are described herein by way of example, those skilled in the art will recognize that the implementations are not limited to the examples or figures described. It should be understood that the figures and detailed description thereto are not intended to limit implementations to the particular form disclosed but, on the contrary, the intention is to cover all modifications, equivalents, and alternatives falling within the spirit and scope as defined by the appended claims. The headings used herein are for organizational purposes only and are not meant to be used to limit the scope of the description or the claims. As used throughout this application, the word &quot;may&quot; is used in a permissive sense (i.e., meaning having the potential to), rather than the mandatory sense (i.e., meaning must). Similarly, the words &quot;include&quot;, &quot;including&quot;, and &quot;includes&quot; mean &quot;including, but not limited to&quot;. </p><p>DETAILED DESCRIPTION</p><p>[0006]    A videoconferencing system may include multiple cameras with different fields-of-view (FOVs) of a conference room. These cameras may be operated to frame the conference room, a person in the conference room, multiple persons in the conference room, and so forth, depending on the FOV of each camera and default settings. For example, frames of images from a first camera with a first FOV may be sent to a far site to zoom on a single person that is talking while frames of images from a second camera with a wider FOV may be sent to the far site to frame multiple persons talking or to frame all persons in the conference room. When frames from different cameras are used, the resulting transition from one frame to the next frame may not be handled very smoothly, which results in an unpleasant viewing experience. By analyzing frames to determine a region of interest and determining if a change in camera source is involved, a system may apply one or more transition effects that may help improve the presentation of frames. </p><p>[0007]    Frames, such as still images captured by a video stream, are acquired by cameras in a videoconferencing system. These frames are processed and analyzed by one or more computer vision systems to extract numerical or symbolic information. In some embodiments, these computer vision systems include neural networks that help identify persons in a conference room and their corresponding location. In particular, when frames are inputted to a neural network, the output of the neural network may provide information of features of persons detected in the frames, such as faces, bodies, or heads of such persons. In one example, bounding boxes may be outputted by the neural network to identify the faces of persons in the conference room. </p><p>[0008]    In a similar manner, audio acquired from the microphones in a videoconference system may also be analyzed to determine the source location of sound detected by the microphones. In some embodiments, these sounds may correspond to voices of persons talking during a videoconference. An audio system may process this audio data to determine a horizontal or vertical position of a source location of the sound that is detected. </p><p>[0009]    By combining the feature data and the sound source data, a state may be determined for frames of images acquired by the cameras of a videoconferencing system. For example, the combination of bounding boxes and the horizontal or vertical position of a sound due to a voice talking may help determine that one person of a group of persons in a conference room is talking at a particular time. Overtime, such a state may change if other persons are talking, if the current talker stops talking, and so forth. </p><p>[0010]    The state of the frames associated with a videoconference may help identify the type of framing, and corresponding regions of interests, that are desired. For example, a state of one person talking may correspond to framing the current talker, while a different state involving multiple persons talking may correspond to group framing. A state and desired type of framing may help identify a particular camera of the multiple cameras in a videoconferencing system that are desirable to present frames associated with the current state. Given that each camera has a corresponding FOV, the state and desired framing may be used to determine the camera with the best FOV to implement the desired framing. </p><p>[0011]    In some embodiments, a first camera may be used with a FOV that is centered in the conference room, but does not span the entire conference room. For example, the first camera may have a focused center that includes a table and a few persons typically sitting at the table and participating in a videoconference. In some scenarios, this first camera may serve as the default camera and may be of high-resolution. A second camera, such as a wide-angle camera, may also be used in a conference room with a FOV that captures the entire conference room (and thus the entire FOV of the first camera). This wide-angle camera may be used for scenarios where the focus is all of the persons in the room, several persons talking that are far apart, and so forth. In some scenarios, this wide-angle camera is not considered the default camera to use and thus may be of lower resolution than the first camera. In other embodiments, there may be three or more cameras, each with different FOVs of the conference room. Some of these cameras may be part of the same structure or individually positioned within the conference room. </p><p>[0012]    When switching from one state to another state, frames with corresponding regions of interest to be sent to the far site may be acquired from the same camera. In other scenarios, one frame with a first region of interest to be sent to the far site may be acquired by a first camera, while the next frame with a second region of interest may be acquired from a second camera. The transitions between these frames and regions of interest (which are due to changed states during the videoconference) may be unpleasant, particularly when a change in a camera source is involved. </p><p>[0013]    To prevent these unpleasant experiences and to make framing decisions more automatic, an analysis is performed to determine if the different frames involved, and thus the different regions of interest to be used, require a change in a camera source. If no change in camera source is involved, a first frame having a first region of interest may be replaced with the second frame having a second region of interest using an ease transition, as both frames are acquired by the same camera. By contrast, if a change in camera source is involved, a dissolve transition is used instead. The dissolve transition may phase out the presentation of a first frame having the first region of interest, while phasing in the presentation of a second frame having the second region of interest. In some scenarios, this may involve phasing from the presentation of the first frame having the first region of interest, to a white or blank screen or frame, and then from the white or blank screen or frame to the second frame having the second region of interest. These two transition effects, which are dependent upon the change in states, help improve the experience for the viewer. In addition, the framing decisions become more automatic while providing a pleasant experience for the far site. </p><p>[0014]    FIG. 1  illustrates a videoconferencing endpoint 100, according to some embodiments. The videoconferencing apparatus or endpoint 100 communicates with one or more remote endpoints 102 over a network 104. Components of the endpoint 100 include an audio module 106 with an audio codec 108 and has a video module 110 with a video codec 112. Modules 106 and 110 operatively couple to a control module 114 and a network module 116. </p><p>[0015]    During a videoconference, one or more cameras (e.g., camera 118 and camera 120) capture video and provide the captured video to the video module 110 and codec 112 for processing. Some embodiments may include two cameras, while other embodiments include three or more cameras. In one example, one camera (e.g., 118) is a smart camera and one camera (e.g., 120) is not a smart camera. In some examples, two or more cameras (e.g., camera 118 and camera 120) are cascaded such that one camera controls some or all operations of the other camera. In some examples, two or more cameras (e.g., camera 118 and camera 120) are cascaded such that data captured by one camera is used (e.g., by the control module 114) to control some or all operations of the other camera. </p><p>[0016]    In another example, a setup for a conference room may include three or more cameras with different FOVs or partially overlapping FOVs that are positioned within the conference room. These cameras may be included individually or in sets near or around a display screen, on a table, within various corners of the room, and so forth. A location and FOV provided by each camera may be evaluated to determine the camera that could provide the most appropriate face forward view of participants and talkers during a videoconference. In a scenario where a videoconference participant is moving, a first camera with a first FOV may be most appropriate to provide a view of the face of the participant at a first time, while a second camera with a second FOV may be most appropriate to provide a view of the face of the participant at a second time, after the participant has moved. </p><p>[0017]    In yet another example, the endpoint 100 may include only a single camera, such as camera 118, and that camera is a wide angle electronic-pan-tilt-zoom camera. In some examples, when a view subject is zoomed in upon, a sub-portion of the captured image containing the subject is rendered, whereas other portions of the image are not. Additionally, one or more microphones 122 capture audio and provide the audio to the audio module 106 and codec 108 for processing. These microphones 122 can be table or ceiling microphones, or they can be part of a microphone pod or the like. In one or more examples, the microphones 122 are tightly coupled with one or more cameras (e.g., camera 118 and camera 120). The endpoint 100 uses the audio captured with these microphones 122 primarily for the conference audio. </p><p>[0018]    As shown in  FIG. 1 , an endpoint 100 also includes a microphone array 124, in which a subarray 126 is orthogonally arranged with a subarray 128. In some examples, the microphone array 124 also captures audio and provides the audio to the audio module 106 for processing. In some examples, the microphone array 124 includes both vertically and horizontally arranged microphones for determining locations of audio sources, e.g., people who are talking. In some examples, the microphone array 124 includes only horizontally arranged microphones. In some examples, the endpoint 100 uses audio from the microphone array 124 primarily for camera tracking purposes and not for conference audio. In some examples, the endpoint 100 uses audio from the microphone array 124 for both camera tracking and conference audio. </p><p>[0019]    After capturing audio and video, the endpoint 100 encodes the audio and video in accordance with an encoding standard, such as MPEG-4, H.263, H.264 and H.265. Then, the network module 116 outputs the encoded audio and video streams to the remote endpoints 102 via the network 104 using an appropriate protocol. Similarly, the network module 116 receives conference audio and video through the network 104 from the remote endpoints 102 and transmits the received audio and video to their respective codecs 108/112 for processing. The endpoint 100 also includes a loudspeaker 130 which outputs conference audio, and a display 132 that outputs conference video. </p><p>[0020]    In at least one example of this disclosure, the endpoint 100 uses the two or more cameras 118, 120 in an automated and coordinated manner to handle video and views of the videoconference environment dynamically. In some examples, the first camera (e.g. 118) is a fixed electronic pan-tilt-zoom (EPTZ) wide-angle camera, and the second camera 120 is a fixed EPTZ telephoto camera. In other examples, the first camera 118 or the second camera 120 may be manual or EPTZ cameras that are not fixed. In even further examples, the field of view of the telephoto camera 120 is approximately centered on the field of view of the wide-angle camera 118. This centered configuration allows higher resolution images for the central area of the conference room, where the endpoint 100 is generally directed and the participants usually sit. Using the wide-angle camera (e.g. 118), the endpoint 100 captures video of the room or at least a wide or zoomed-out view of the room that would typically include all the videoconference participants 121 as well as some of their surroundings. </p><p>[0021]    According to some examples, the endpoint 100 uses the telephoto camera (e.g., 120) to capture video of one or more participants, including one or more current talkers, in a tight or zoomed-in view. </p><p>[0022]    In some examples, the endpoint 100 alternates between tight views of a talker and wide views of a room. In some examples, the endpoint 100 alternates between two different tight views of the same or different talkers. In some examples, the endpoint 100 will capture a first view of a person with one camera and a second view of the same person with another camera and determine which view is better for sharing with a remote endpoint 102. </p><p>[0023]    In at least one example of this disclosure, the endpoint 100 outputs video from only one of the two cameras 118, 120 at 

#### 7.1.8.2 Import root
* Parse the XML response
* Define namespaces correctly

In [18]:
import xml.etree.ElementTree as ET
import re

# Parse the XML
root = ET.fromstring(description)

# Define namespaces correctly
namespaces = {
    'ftxt': 'http://www.epo.org/fulltext',
    'ops': 'http://ops.epo.org',
}

#### 7.1.8.3 Functions to extract text, expand_figure_range and extract_descriptions
* Extracts and concatenates all text from an XML element and its children
* Extract numeric parts from start and end figure numbers
* Generate a list of figure numbers in the range, preserving the prefix
* Iterate through all 'p' elements in the XML tree
* Check if the text starts with a section header
* Find all figure references in the text
* Add figure descriptions to the figures dictionary

In [19]:
def extract_text(element):
    # Extracts and concatenates all text from an XML element and its children
    # Removes leading and trailing whitespace    
    return ''.join(element.itertext()).strip()

def expand_figure_range(start, end):
    try:
        # Extract numeric parts from start and end figure numbers
        start_num = int(re.search(r'\d+', start).group())
        end_num = int(re.search(r'\d+', end).group())
        # Generate a list of figure numbers in the range, preserving the prefix
        return [f"{start[:-1]}{i}" for i in range(start_num, end_num + 1)]  # Keep the prefix of the figure number
    except Exception as e:
        # Handle any errors during range expansion
        print(f"Error expanding range: {e}. Start: {start}, End: {end}")
        return []  # Return an empty list if there's an error

def extract_descriptions(root):
    # Initialize dictionaries to store section and figure descriptions
    sections = {}
    figures = {}
    current_section = None
    description = []
    
    # Iterate through all 'p' elements in the XML tree
    for p in root.findall('.//ftxt:p', namespaces):
        # Extract text from the element and remove citation numbers
        text = extract_text(p)
        text = re.sub(r'\[\d{4}\]', '', text).strip()
        
        # Check if the text starts with a section header
        section_match = re.match(r'^(PRIORITY|BACKGROUND|BRIEF DESCRIPTION OF FIGURES|DETAILED DESCRIPTION)', text, re.I)
        
        # Find all figure references in the text
        figure_matches = re.findall(r'(Fig\.?|FIG\.?|Figure|Figures?)\s*([\dA-Z]+(?:[-–]\s*[\dA-Z]+)?(?:\s+to\s+[\dA-Z]+)?)', text, re.I)

        if section_match:
            # If a new section is found, save the previous section and start a new one
            if current_section:
                sections[current_section] = ' '.join(description).strip()
            current_section = section_match.group(1).strip()
            description = [text]
        elif figure_matches:
            # Process figure references. Collect figure descriptions only if the reference is valid
            for fig_prefix, fig_number in figure_matches:
                fig_number = fig_number.strip()
                # Ensure figure number is valid (only contains numbers and letters)
                if re.search(r'\d', fig_number):  # Ensure figure number contains a digit
                    if '-' in fig_number or '–' in fig_number:
                        # Handle figure ranges with hyphens
                        start, end = re.split(r'[-–]\s*', fig_number)
                        expanded_figures = expand_figure_range(start, end)
                        for fig in expanded_figures:
                            if fig and fig not in figures:  # Avoid duplicates
                                figures[fig] = text.strip()
                    elif 'to' in fig_number:
                        # Handle figure ranges with 'to'
                        start, end = fig_number.split('to')
                        expanded_figures = expand_figure_range(start.strip(), end.strip())
                    else:
                        # Single figure reference
                        expanded_figures = [fig_number]
                    
                    # Add figure descriptions to the figures dictionary
                    for fig in expanded_figures:
                        if fig and fig not in figures:  # Avoid duplicates
                            figures[fig] = text.strip()
                    else:
                        if fig_number not in figures:  # Avoid duplicates
                            figures[fig_number] = text.strip()
        elif current_section:
            # If not a section header or figure reference, add to current section description
            description.append(text)

    if current_section:
        sections[current_section] = ' '.join(description).strip()

    return sections, figures

#### 7.1.8.4 Process and print the description
* Extract descriptions and figure descriptions
* Display an overview of labeled sections
* Print first 200 characters for preview

In [20]:
# Extract descriptions and figure descriptions
sections, figures = extract_descriptions(root)

# Display an overview of labeled sections
print(f"Total sections found: {len(sections)}\n")
print("Overview of Labeled Sections:")

for section, content in sections.items():
    print(f"\n{section}:")
    print(f"   {content[:200]}...")  # Print first 200 characters for preview

Error expanding range: 'NoneType' object has no attribute 'group'. Start: 17, End: three
Total sections found: 4

Overview of Labeled Sections:

PRIORITY:
   PRIORITY This application claims priority to,  U.S. Provisional Patent Application No. 63/202,527, filed on June 15, 2021 , entitled "Telephoto and Wide-Angle Automatic Framing", which is hereby incor...

BACKGROUND:
   BACKGROUND In a videoconference, framing refers to the view or frame provided to the far end or site. Originally, framing was performed manually, first locally and then remotely. The pan, tilt, and zo...

BRIEF DESCRIPTION OF FIGURES:
   BRIEF DESCRIPTION OF FIGURES...

DETAILED DESCRIPTION:
   DETAILED DESCRIPTION A videoconferencing system may include multiple cameras with different fields-of-view (FOVs) of a conference room. These cameras may be operated to frame the conference room, a pe...

#### 7.1.8.5 Display an overview of figures

In [21]:
# Display an overview of figures
print(f"\nTotal figures found: {len(figures)}")
print("\nOverview of Figures:")

def sort_key(item):
    figure_num = re.findall(r'\d+', item[0])
    if figure_num:
        return (int(figure_num[0]), item[0])
    return (float('inf'), item[0])  # Place non-numeric figures at the end

for figure, description in sorted(figures.items(), key=sort_key):
    # Check if figure is a redundant reference
    if re.match(r'Figure\s+\d+', figure) and f"Figure {figure.split()[1]}:" in figures:
        continue  # Skip if it's redundant
    print(f"\nFigure {figure}:")
    print(f"   {description[:200]}...")  # Print first 200 characters for preview

Total figures found: 26

Overview of Figures:

Figure 1:
   The detailed description is set forth with reference to the accompanying figures. In the figures, the left-most digit(s) of a reference number identifies the figure in which the reference number first...

Figure 2:
   The detailed description is set forth with reference to the accompanying figures. In the figures, the left-most digit(s) of a reference number identifies the figure in which the reference number first...

Figure 3:
   The detailed description is set forth with reference to the accompanying figures. In the figures, the left-most digit(s) of a reference number identifies the figure in which the reference number first...

Figure 4:
   The detailed description is set forth with reference to the accompanying figures. In the figures, the left-most digit(s) of a reference number identifies the figure in which the reference number first...

Figure 5:
   The detailed description is set forth with reference to the accompanying figures. In the figures, the left-most digit(s) of a reference number identifies the figure in which the reference number first...

Figure 5A:
   The detailed description is set forth with reference to the accompanying figures. In the figures, the left-most digit(s) of a reference number identifies the figure in which the reference number first...

Figure 5B:
   Operation of the flowchart of  Fig. 5A  is illustrated in  Figs. 5B-5E . In  Fig. 5B , a starting frame 530 and an ending frame 532 are shown. As both frames 530 and 532 are within the telephoto camer...

Figure 5C:
   Operation of the flowchart of  Fig. 5A  is illustrated in  Figs. 5B-5E . In  Fig. 5B , a starting frame 530 and an ending frame 532 are shown. As both frames 530 and 532 are within the telephoto camer...

Figure 5D:
   In  Fig. 5D , the starting frame 530 is within the field of view of the telephoto camera 120, while an ending frame 536 extends past the field of view of the telephoto camera 120 and thus is only in t...

Figure 5E:
   In  Fig. 5D , the starting frame 530 is within the field of view of the telephoto camera 120, while an ending frame 536 extends past the field of view of the telephoto camera 120 and thus is only in t...

Figure 5F:
   Fig. 5F  illustrates a starting frame 540 covering participant 410 and an endingframe 542, covering participants 404 and 406. As both frames extend past the field of view of the telephoto camera 120 a...

Figure 6:
   The detailed description is set forth with reference to the accompanying figures. In the figures, the left-most digit(s) of a reference number identifies the figure in which the reference number first...

Figure 7:
   The detailed description is set forth with reference to the accompanying figures. In the figures, the left-most digit(s) of a reference number identifies the figure in which the reference number first...

Figure 8:
   The detailed description is set forth with reference to the accompanying figures. In the figures, the left-most digit(s) of a reference number identifies the figure in which the reference number first...

Figure 9:
   The detailed description is set forth with reference to the accompanying figures. In the figures, the left-most digit(s) of a reference number identifies the figure in which the reference number first...

Figure 10:
   The detailed description is set forth with reference to the accompanying figures. In the figures, the left-most digit(s) of a reference number identifies the figure in which the reference number first...

Figure 10A:
   The detailed description is set forth with reference to the accompanying figures. In the figures, the left-most digit(s) of a reference number identifies the figure in which the reference number first...

Figure 11:
   The detailed description is set forth with reference to the accompanying figures. In the figures, the left-most digit(s) of a reference number identifies the figure in which the reference number first...

Figure 12:
   The detailed description is set forth with reference to the accompanying figures. In the figures, the left-most digit(s) of a reference number identifies the figure in which the reference number first...

Figure 13:
   The detailed description is set forth with reference to the accompanying figures. In the figures, the left-most digit(s) of a reference number identifies the figure in which the reference number first...

Figure 14:
   The detailed description is set forth with reference to the accompanying figures. In the figures, the left-most digit(s) of a reference number identifies the figure in which the reference number first...

Figure 15:
   The detailed description is set forth with reference to the accompanying figures. In the figures, the left-most digit(s) of a reference number identifies the figure in which the reference number first...

Figure 16:
   The detailed description is set forth with reference to the accompanying figures. In the figures, the left-most digit(s) of a reference number identifies the figure in which the reference number first...

Figure 17:
   The detailed description is set forth with reference to the accompanying figures. In the figures, the left-most digit(s) of a reference number identifies the figure in which the reference number first...

Figure 17  to three:
   The detailed description is set forth with reference to the accompanying figures. In the figures, the left-most digit(s) of a reference number identifies the figure in which the reference number first...

Figure 18:
   The detailed description is set forth with reference to the accompanying figures. In the figures, the left-most digit(s) of a reference number identifies the figure in which the reference number first...

### 7.1.9 Example of fetching abstract data
This example retrieves abstract data (endpoint="abstract") for a published patent identified by its document number stored in the Docdb object.

In [22]:
# Fetch description for a publication
abstract = client.published_data(
        reference_type='publication', # application, publication
        input=models.Docdb("4106326", "EP", "A1", date=None),
        endpoint='abstract',
        constituents=[],
        output_type="raw"
    )
pprint(abstract)

('<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" '
 'href="../../../../../style/exchange.xsl"?>\n'
 '<ops:world-patent-data xmlns="http://www.epo.org/exchange" '
 'xmlns:ops="http://ops.epo.org" xmlns:xlink="http://www.w3.org/1999/xlink">\n'
 '    <exchange-documents>\n'
 '        <exchange-document country="EP" doc-number="4106326" kind="A1">\n'
 '            <bibliographic-data>\n'
 '                <publication-reference>\n'
 '                    <document-id document-id-type="docdb">\n'
 '                        <country>EP</country>\n'
 '                        <doc-number>4106326</doc-number>\n'
 '                        <kind>A1</kind>\n'
 '                        <date>20221221</date>\n'
 '                    </document-id>\n'
 '                    <document-id document-id-type="epodoc">\n'
 '                        <doc-number>EP4106326</doc-number>\n'
 '                        <date>20221221</date>\n'
 '                    </document-id>\n'
 '                </publication-reference>\n'
 '                <parties/>\n'
 '            </bibliographic-data>\n'
 '            <abstract lang="en">\n'
 '                <p>A videoconferencing system includes different cameras '
 'with different fields-of-view (FOVs). Frames of images acquired by these '
 'cameras may be processed to determine states, such as number of users '
 'present, talking, and so forth. Based on these states, frames from one '
 'camera may be selected to send to a far site. If the two states indicate no '
 'change in camera source from a first time to a second time, the current '
 'frame from the first camera that is sent to the far site is followed by '
 'another frame from the same camera. If the two states indicate a change in '
 'camera source from the first time to the second time, the current frame from '
 'the first camera that is sent to the far site is followed by a frame from '
 'the different camera. Depending on the two states and the cameras used, '
 'different transition effects may be applied to improve presentation.</p>\n'
 '            </abstract>\n'
 '        </exchange-document>\n'
 '    </exchange-documents>\n'
 '</ops:world-patent-data>')

In [23]:
import xml.etree.ElementTree as ET
import re

# Define namespaces correctly
namespace = {'ops': 'http://ops.epo.org', 'ex': 'http://www.epo.org/exchange'}

# Parse the XML
root = ET.fromstring(abstract)

# Extract bibliographic data
doc_info = root.find('.//ex:document-id[@document-id-type="docdb"]', namespace)
country = doc_info.find('ex:country', namespace).text
doc_number = doc_info.find('ex:doc-number', namespace).text
kind = doc_info.find('ex:kind', namespace).text
date = doc_info.find('ex:date', namespace).text

# Extract abstract and language
abstract_elem = root.find('.//ex:abstract', namespace)
abstract_lang = abstract_elem.attrib['lang']
abstract_text = abstract_elem.find('ex:p', namespace).text

# Display the extracted information
print(f"Country: {country}")
print(f"Document Number: {doc_number}")
print(f"Kind: {kind}")
print(f"Publication Date: {date}")
print(f"Abstract Language: {abstract_lang}")
print(f"Abstract Text: {abstract_text}")

Country: EP
Document Number: 4106326
Kind: A1
Publication Date: 20221221
Abstract Language: en
Abstract Text: A videoconferencing system includes different cameras with different fields-of-view (FOVs). Frames of images acquired by these cameras may be processed to determine states, such as number of users present, talking, and so forth. Based on these states, frames from one camera may be selected to send to a far site. If the two states indicate no change in camera source from a first time to a second time, the current frame from the first camera that is sent to the far site is followed by another frame from the same camera. If the two states indicate a change in camera source from the first time to the second time, the current frame from the first camera that is sent to the far site is followed by a frame from the different camera. Depending on the two states and the cameras used, different transition effects may be applied to improve presentation.

In [24]:
# Fetch biblio and abstract for a publication
abstract = client.published_data(
        reference_type='publication', # application, publication
        input=models.Docdb("4106326", "EP", "A1", date=None),
        endpoint="biblio",
        constituents=["abstract"],
        output_type="dataframe"
        )
display(abstract)

# Check if the abstract DataFrame is not empty before proceeding
if not abstract.empty:
    # Extract the application number from the 'bibliographic-data|application-reference' column
    app_ref = abstract.iloc[0]['bibliographic-data|application-reference']
    
    appln_auth = None
    for doc_id in app_ref['document-id']:
        if doc_id['@document-id-type'] == 'docdb':
            appln_auth = doc_id['country']
            break  # Found the appln_auth, no need to continue
    
    # Extract appln_nr from the document-id list
    appln_number = None
    for doc_id in app_ref['document-id']:
        if doc_id['@document-id-type'] == 'docdb':
            appln_number = doc_id['doc-number']
            break  # Found the appln_number, no need to continue
            
    appln_kind = None
    for doc_id in app_ref['document-id']:
        if doc_id['@document-id-type'] == 'docdb':
            appln_kind = doc_id['kind']
            break  # Found the appln_kind, no need to continue
            
    # Extract publication date from 'bibliographic-data|publication-reference'
    pub_ref = abstract.iloc[0]['bibliographic-data|publication-reference']
    publication_date = None
    for doc_id in pub_ref['document-id']:
        if doc_id['@document-id-type'] == 'docdb':
            publication_date = doc_id['date']  # Extracting the publication date
            break  # Found the publication date, no need to continue

    # Example structure for TLS203-like format
    tls203_format = pd.DataFrame({      
        'docdb_appln_nr': [f"{appln_auth}.{appln_number}.{appln_kind}"],  # Application number (publication number here)
        'epodoc_appln_nr': [f"{appln_auth}{appln_number}{appln_kind}"],  # Application number (publication number here)          
        'abstract_text': [abstract.iloc[0]['abstract|p']],  # Extracting abstract text from 'abstract' DataFrame
        'abstract_lg': [abstract.iloc[0]['abstract|lang'].upper()]  # Extracting abstract language from 'abstract' DataFrame
    })

    # Adjusting pandas settings to show full text without truncation
    pd.set_option('display.max_colwidth', None)

    # Displaying the TLS203-like DataFrame
    print("tls203_format:", tls203_format)

    display(tls203_format)

,system,family-id,country,doc-number,kind,bibliographic-data|publication-reference,bibliographic-data|classifications-ipcr,bibliographic-data|patent-classifications,bibliographic-data|application-reference,bibliographic-data|priority-claims,bibliographic-data|parties,bibliographic-data|invention-title,bibliographic-data|references-cited,abstract|lang,abstract|p
0,ops.epo.org,82067485,EP,4106326,A1,{'document-id': [{'@document-id-type': 'docdb'...,"{'classification-ipcr': {'@sequence': '1', 'te...","{'patent-classification': [{'@sequence': '1', ...","{'@doc-id': '574299984', 'document-id': [{'@do...","{'priority-claim': [{'@sequence': '1', '@kind'...",{'applicants': {'applicant': [{'@sequence': '1...,"[{'@lang': 'de', '#text': 'AUTOMATISCHES FRAMI...","{'citation': [{'@cited-phase': 'undefined', '@...",en,A videoconferencing system includes different ...

tls203_format:   docdb_appln_nr epodoc_appln_nr  \
0  EP.22179301.A     EP22179301A

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            abstract_text  \
0  A videoconferencing system includes different cameras with different fields-of-view (FOVs). Frames of images acquired by these cameras may be processed to determine states, such as number of users present, talking, and so forth. Based on these states, frames from one camera may be selected to send to a far site. If the two states indicate no change in camera source from a first time to a second time, the current frame from the first camera that is sent to the far site is followed by another frame from the same camera. If the two states indicate a change in camera source from the first time to the second time, the current frame from the first camera that is sent to the far site is followed by a frame from the different camera. Depending on the two states and the cameras used, different transition effects may be applied to improve presentation.

  abstract_lg
0          EN

,docdb_appln_nr,epodoc_appln_nr,abstract_text,abstract_lg
0,EP.22179301.A,EP22179301A,"A videoconferencing system includes different cameras with different fields-of-view (FOVs). Frames of images acquired by these cameras may be processed to determine states, such as number of users present, talking, and so forth. Based on these states, frames from one camera may be selected to send to a far site. If the two states indicate no change in camera source from a first time to a second time, the current frame from the first camera that is sent to the far site is followed by another frame from the same camera. If the two states indicate a change in camera source from the first time to the second time, the current frame from the first camera that is sent to the far site is followed by a frame from the different camera. Depending on the two states and the cameras used, different transition effects may be applied to improve presentation.",EN