# The REG112_LICENSEE_STATES table

Welcome to table **REG112_LICENSEE_STATES** in PATSTAT Register. A license might be valid for all states which are covered by a patent, or only by a subset of these countries. In the latter case this table lists the countries for which the license is valid.

In [1]:
from epo.tipdata.patstat import PatstatClient
from epo.tipdata.patstat.database.models import REG112_LICENSEE_STATES
from sqlalchemy import func
import pandas as pd

# Initialise the PATSTAT client
patstat = PatstatClient(env='PROD')

# Access ORM
db = patstat.orm()

## ID (Primary Key)

Technical identifier for an application, without business meaning. Its values will not change from one PATSTAT edition to the next.

In [2]:
i = db.query(
    REG112_LICENSEE_STATES.id
).limit(1000)

df = patstat.df(i)
df

           id
0    20806108
1    12780583
2    18895921
3    11743909
4    20179644
..        ...
995  11382180
996   7075843
997  14778778
998  12177357
999  19835757

[1000 rows x 1 columns]

## BULLETIN_YEAR

For actions that have been published in the European Patent Bulletin, it is the year of the publication in the European Patent Bulletin. The default value is 0, used for applications that are not published or for which the year is not known. The format is YYYY otherwise.

In [3]:
years = db.query(
    REG112_LICENSEE_STATES.bulletin_year,
    REG112_LICENSEE_STATES.id
).limit(1000)

years_df = patstat.df(years)
years_df

     bulletin_year        id
0             2024  20806108
1                0  12780583
2                0  18895921
3                0  11743909
4             2022  20179644
..             ...       ...
995              0  11382180
996              0   7075843
997           2019  14778778
998              0  12177357
999           2024  19835757

[1000 rows x 2 columns]

## BULLETIN_NR

This is the issue number of the European Patent Bulletin for actions that have been published in it. This attribute indicates the calendar week the European Patent Bulletin was published. The default value 0 is used when the attribute `bulletin_year` is 0.

In [4]:
bulletin_nr = db.query(
    REG112_LICENSEE_STATES.id,
    REG112_LICENSEE_STATES.bulletin_nr,
    REG112_LICENSEE_STATES.bulletin_year
).limit(100)

bulletin_nr_df = patstat.df(bulletin_nr)
bulletin_nr_df

          id  bulletin_nr  bulletin_year
0   20806108           11           2024
1   12780583            0              0
2   18895921            0              0
3   11743909            0              0
4   20179644            8           2022
..       ...          ...            ...
95  17716068            0              0
96   4768442            0              0
97   6821614            0              0
98  18785606           31           2024
99  18756223            0              0

[100 rows x 3 columns]

## LICENSEE_SEQ_NR

Serial number of license / sub-license. The first two digits are the serial number of a main license and the optional other two digits represent the serial number of a sub-license. Unlike table REG111_LICENSEE, in table REG112_LICENSEE_STATES the value 'deleted' does not occur.

In [5]:
licensee = db.query(
    REG112_LICENSEE_STATES.id,
    REG112_LICENSEE_STATES.licensee_seq_nr
).limit(100)

licensee_df = patstat.df(licensee)
licensee_df

          id licensee_seq_nr
0   20806108          01  00
1   12780583              02
2   18895921              02
3   11743909              01
4   20179644          01  00
..       ...             ...
95  17716068              01
96   4768442              01
97   6821614              01
98  18785606          03  00
99  18756223              01

[100 rows x 2 columns]

## LICENSEE_COUNTRY

This attribute indicates the countries/territories where the license is valid in case it is not for all designated states.

There is one record in the table per country/territory, meaning that if we want to retrieve all the designated staes for one application than we get several rows of the dataset, one per each of the designates states. Assume that we want to filter all the designates states for application 6808482.

In [6]:
licensee_country = db.query(
    REG112_LICENSEE_STATES.licensee_country,
    REG112_LICENSEE_STATES.id
).filter(
    REG112_LICENSEE_STATES.id == 6808482
)

country_df = patstat.df(licensee_country)
country_df

   licensee_country       id
0                GR  6808482
1                BG  6808482
2                LT  6808482
3                NL  6808482
4                GB  6808482
..              ...      ...
85               CY  6808482
86               SK  6808482
87               FR  6808482
88               FI  6808482
89               CY  6808482

[90 rows x 2 columns]