# The REG113_TERMS_OF_GRANT table

Welcome to table **REG113_TERMS_OF_GRANT** in PATSTAT Register. This table contains information about lapses during the opposition phase or during the period when opposition can be filed. It is worth mentioning that the EPO is not the "owner" of any lapses in the national phase of a patent. Therefore, this information is not included.

In [1]:
from epo.tipdata.patstat import PatstatClient
from epo.tipdata.patstat.database.models import REG113_TERMS_OF_GRANT
from sqlalchemy import func
import pandas as pd

# Initialise the PATSTAT client
patstat = PatstatClient(env='PROD')

# Access ORM
db = patstat.orm()

## Id (primary key)

Technical identifier for an application, without business meaning. Its values will not change from one PATSTAT edition to the next.

In [2]:
i = db.query(
    REG113_TERMS_OF_GRANT.id
).limit(1000)

df = patstat.df(i)
df

           id
0    96933178
1    16908739
2    14814785
3    11177095
4    12813672
..        ...
995  10730797
996  20771218
997  10011069
998  11772540
999  10772277

[1000 rows x 1 columns]

## CHANGE_DATE

It is the date when the record was saved in the database.

In [3]:
change_date = db.query(
    REG113_TERMS_OF_GRANT.change_date,
    REG113_TERMS_OF_GRANT.id
).limit(100)

change_date_df = patstat.df(change_date)
change_date_df

   change_date        id
0   2024-09-27  18704931
1   2014-07-18  10170369
2   2008-12-12   2425200
3   2015-09-04   9752738
4   2010-01-01  95943660
..         ...       ...
95  2013-10-04   4748081
96  2013-10-04   7866284
97  2024-09-27  18766993
98  2020-07-10  99930982
99  2011-09-30   6014105

[100 rows x 2 columns]

## BULLETIN_YEAR

For actions that have been published in the European Patent Bulletin, it is the year of the publication in the European Patent Bulletin. The default value is 0, used for applications that are not published or for which the year is not known. The format is YYYY otherwise.

In [4]:
years = db.query(
    REG113_TERMS_OF_GRANT.bulletin_year,
    REG113_TERMS_OF_GRANT.id
).limit(1000)

years_df = patstat.df(years)
years_df

     bulletin_year        id
0             2024  18704931
1             2014  10170369
2             2009   2425200
3             2015   9752738
4             2010  95943660
..             ...       ...
995           2018  13178243
996           2014   5753713
997           2022  12163574
998           2022  17714285
999           2013   4805472

[1000 rows x 2 columns]

## BULLETIN_NR

This is the issue number of the European Patent Bulletin for actions that have been published in it. This attribute indicates the calendar week the European Patent Bulletin was published. The default value 0 is used when the attribute `bulletin_year` is 0.

In [5]:
bulletin_nr = db.query(
    REG113_TERMS_OF_GRANT.id,
    REG113_TERMS_OF_GRANT.bulletin_nr,
    REG113_TERMS_OF_GRANT.bulletin_year
).limit(100)

bulletin_nr_df = patstat.df(bulletin_nr)
bulletin_nr_df

          id  bulletin_nr  bulletin_year
0   10854716           33           2020
1   13179495           32           2022
2   20185318           36           2025
3   14822189           31           2022
4   17924186           44           2024
..       ...          ...            ...
95  17174763           42           2024
96  15753867           41           2024
97  17770513           42           2024
98   9015499           29           2018
99  17196418           36           2025

[100 rows x 3 columns]

## LAPSED_COUNTRY

The office country code for which a lapse occurred during the opposition phase or the period when opposition can be filed.

Suppose that we want to get all the countries for which a lapse occurred for application 15184347.

In [6]:
lapses = db.query(
    REG113_TERMS_OF_GRANT.id,
    REG113_TERMS_OF_GRANT.lapsed_country
).filter(
    REG113_TERMS_OF_GRANT.id == 15184347
)

lapses_df = patstat.df(lapses)
lapses_df

          id lapsed_country
0   15184347             LT
1   15184347             TR
2   15184347             RS
3   15184347             IT
4   15184347             DK
5   15184347             BG
6   15184347             RO
7   15184347             FI
8   15184347             SI
9   15184347             MC
10  15184347             PL
11  15184347             MT
12  15184347             HR
13  15184347             CZ
14  15184347             LV
15  15184347             BE
16  15184347             CY
17  15184347             NO
18  15184347             AL
19  15184347             HU
20  15184347             IE
21  15184347             LI
22  15184347             ES
23  15184347             SK
24  15184347             NL
25  15184347             EE
26  15184347             AT
27  15184347             PT
28  15184347             SE
29  15184347             MK
30  15184347             GR
31  15184347             LU
32  15184347             SM
33  15184347             CH
34  15184347             IS

## LAPSED_DATE

The date when a lapse occurred in one of the designated states during the opposition phase or the period when opposition can be filed.

We can add this check to the previous example.

In [7]:
lapses_dates = db.query(
    REG113_TERMS_OF_GRANT.id,
    REG113_TERMS_OF_GRANT.lapsed_country,
    REG113_TERMS_OF_GRANT.lapsed_date
).filter(
    REG113_TERMS_OF_GRANT.id == 15184347
)

lapses_dates_df = patstat.df(lapses_dates)
lapses_dates_df

          id lapsed_country lapsed_date
0   15184347             RS  2019-04-17
1   15184347             LT  2019-04-17
2   15184347             MT  2019-04-17
3   15184347             DK  2019-04-17
4   15184347             BG  2019-07-17
5   15184347             IT  2019-04-17
6   15184347             LI  2019-09-30
7   15184347             ES  2019-04-17
8   15184347             RO  2019-04-17
9   15184347             FI  2019-04-17
10  15184347             AL  2019-04-17
11  15184347             MC  2019-04-17
12  15184347             IE  2019-09-08
13  15184347             TR  2019-04-17
14  15184347             CH  2019-09-30
15  15184347             IS  2019-08-17
16  15184347             HU  2015-09-08
17  15184347             SI  2019-04-17
18  15184347             AT  2019-04-17
19  15184347             PT  2019-08-17
20  15184347             PL  2019-04-17
21  15184347             LU  2019-09-08
22  15184347             SM  2019-04-17
23  15184347             CZ  2019-04-17
24  15184347             LV  2019-04-17
25  15184347             BE  2019-09-30
26  15184347             CY  2019-04-17
27  15184347             NO  2019-07-17
28  15184347             SK  2019-04-17
29  15184347             NL  2019-04-17
30  15184347             HR  2019-04-17
31  15184347             EE  2019-04-17
32  15184347             SE  2019-04-17
33  15184347             MK  2019-04-17
34  15184347             GR  2019-07-18