# The REG107_PARTIES table

Welcome to table **REG107_PARTIES** in PATSTAT Register. This table contain details about applicants, inventors and agents / legal representatives.

Specifically, we can find information about the country, the name, and the address of the parties.

In [1]:
from epo.tipdata.patstat import PatstatClient
from epo.tipdata.patstat.database.models import REG107_PARTIES
from sqlalchemy import func
import pandas as pd

# Initialise the PATSTAT client
patstat = PatstatClient(env='PROD')

# Access ORM
db = patstat.orm()

## ID (Primary Key)

Technical identifier for an application, without business meaning. Its values will not change from one PATSTAT edition to the next.

In [2]:
i = db.query(
    REG107_PARTIES.id
).limit(1000)

df = patstat.df(i)
df

           id
0    22745149
1    15726078
2    20830107
3    20172637
4    13002426
..        ...
995   6780259
996  12783211
997  20915193
998  21781221
999   8780578

[1000 rows x 1 columns]

## IS_LATEST

Y/N flag. Y indicates the latest, i.e. current or most recent, set of applicants / inventors / representatives / opponents.

In [3]:
is_latest = db.query(
    REG107_PARTIES.id,
    REG107_PARTIES.is_latest
).limit(100)

is_latest_df = patstat.df(is_latest)
is_latest_df

          id is_latest
0   12853978         Y
1   19738683         Y
2   22845339         Y
3    1903120         Y
4   23703866         Y
..       ...       ...
95   5706813         N
96  10732781         Y
97   7730672         Y
98  14729335         Y
99  22913339         Y

[100 rows x 2 columns]

We can count how many applications in the database have the latest set of applicants / inventors / representatives / opponents.

In [4]:
latest = db.query(
    REG107_PARTIES.is_latest,
    func.count(REG107_PARTIES.id).label('total_applications')
).group_by(
    REG107_PARTIES.is_latest
).order_by(
    func.count(REG107_PARTIES.id).desc()
)

latest_df = patstat.df(latest)
latest_df

  is_latest  total_applications
0         Y            32470813
1         N            10232493

## CHANGE_DATE

It is the date on which the record was saved in the database.

In [5]:
change_date = db.query(
    REG107_PARTIES.change_date,
    REG107_PARTIES.id
).limit(100)

change_date_df = patstat.df(change_date)
change_date_df

   change_date        id
0   1989-06-24  88900679
1   1981-10-17  81103078
2   2008-12-12   7761385
3   2015-02-24  13708791
4   2014-12-16  11878909
..         ...       ...
95  2000-05-12  95810378
96  2023-04-14  21735580
97  1995-02-10  94114487
98  2011-04-08   5794729
99  2015-04-17  13816500

[100 rows x 2 columns]

## BULLETIN_YEAR

For actions that have been published in the European Patent Bulletin, it is the year of the publication in the European Patent Bulletin. The default value is 0, used for applications that are not published or for which the year is not known. The format is YYYY otherwise.

In [6]:
years = db.query(
    REG107_PARTIES.bulletin_year,
    REG107_PARTIES.id
).limit(1000)

years_df = patstat.df(years)
years_df

     bulletin_year        id
0             2020  12853978
1                0  19738683
2             2024  22845339
3                0   1903120
4             2024  23703866
..             ...       ...
995              0  16906143
996              0  16723228
997              0  10808350
998           1992  91311713
999              0  18746217

[1000 rows x 2 columns]

## BULLETIN_NR

This is the issue number of the European Patent Bulletin for actions that have been published in it. This attribute indicates the calendar week the European Patent Bulletin has been published. The default value 0 is used when the attribute `bulletin_year` is 0.

In [7]:
bulletin_nr = db.query(
    REG107_PARTIES.id,
    REG107_PARTIES.bulletin_nr,
    REG107_PARTIES.bulletin_year
).limit(100)

bulletin_nr_df = patstat.df(bulletin_nr)
bulletin_nr_df

          id  bulletin_nr  bulletin_year
0   12799273           38           2015
1    8781676           30           2010
2   21173688           46           2022
3   18180741            1           2019
4    9793562           46           2011
..       ...          ...            ...
95  97911104           42           2000
96  21786028            0              0
97  92912156            0              0
98   7726298           42           2008
99  90110978           51           1990

[100 rows x 3 columns]

## TYPE

Type of party ("A" for applicant / "I" for inventor / "R" for legal representative).

Let's see what the most common type of party is.

In [8]:
type_party = db.query(
    REG107_PARTIES.type,
    func.count(REG107_PARTIES.id).label('number_of_applications')
).group_by(
    REG107_PARTIES.type
).order_by(
    func.count(REG107_PARTIES.id).desc()
)

type_party_df = patstat.df(type_party)
type_party_df

  type  number_of_applications
0    I                22514123
1    A                11286076
2    R                 8903107

## WISHES_TO_BE_PUBLISHED

An inventor can agree to waive his entitlement for designation. The EP register then does not publish name or address of those inventors. Nevertheless, it is explicit that there is an inventor, even if name and address are not given. Therefore, this attribute indicates that the inventor has agreed to waive his entitlement for designation.

The corresponding field is either empty or 'N'.

In [9]:
wish = db.query(
    REG107_PARTIES.wishes_to_be_published,
    func.count(REG107_PARTIES.id).label('number_of_applications')
).group_by(
    REG107_PARTIES.wishes_to_be_published
).order_by(
    func.count(REG107_PARTIES.id).desc()
)

wish_df = patstat.df(wish)
wish_df

  wishes_to_be_published  number_of_applications
0                                       42689082
1                      N                   14224

## SEQ_NR

Sequence number of party (concerns applicant, inventor and legal representative). All applicants (one or more) of an application at a certain point of time are regarded as a “set” of applicants. The `seq_nr` defines the order of applicants within this set. The same applies to inventors and legal representatives (see attribute `type`).

In [10]:
seq = db.query(
    REG107_PARTIES.id,
    REG107_PARTIES.seq_nr
).limit(1000)

seq_df = patstat.df(seq)
seq_df

           id  seq_nr
0    12853978       1
1    19738683       1
2    22845339       2
3     1903120       1
4    23703866       2
..        ...     ...
995  16906143       1
996  16723228       2
997  10808350       1
998  91311713       1
999  18746217       2

[1000 rows x 2 columns]

## DESIGNATION

Type of designation. Default value apart, i.e. empty string, this attribute can assume two values: 'all' and 'as indicated'.

In [11]:
desig = db.query(
    REG107_PARTIES.designation,
    func.count(REG107_PARTIES.id).label('number_of_applications')
).group_by(
    REG107_PARTIES.designation
).order_by(
    func.count(REG107_PARTIES.id).desc()
)

desig_df = patstat.df(desig)
desig_df

    designation  number_of_applications
0                              31417230
1           all                10022184
2  as-indicated                 1263892

## CUSTOMER_ID

The identifier of a customer, which can be a legal or natural person. If a customer has several roles (applicant, inventor, representative, licensee, opponent) he usually has several `customer_id`s.

Not every person has a `customer_id` assigned. Persons which are only inventors (and not e. g. also applicants) do not have a `customer_id`.

In [12]:
customer = db.query(
    REG107_PARTIES.customer_id
).limit(1000)

customer_df = patstat.df(customer)
customer_df

    customer_id
0    0101728904
1    0100111989
2
3
4    0101911627
..          ...
995  0102097314
996
997
998  0100026679
999  0100498557

[1000 rows x 1 columns]

## NAME

Name of a person (natural person or legal person).

In [13]:
name = db.query(
    REG107_PARTIES.name
).limit(100)

name_df = patstat.df(name)
name_df

                                        name
0                            Bateman, Nicola
1                        Alcatel Canada Inc.
2                   KARTHIKEYAN, Chandrabose
3                        CASWELL, William F.
4                              PÁLSSON, Kári
..                                       ...
95                     MILCH, Robert, Austin
96                    Thürer, Andreas, et al
97  MATSUSHITA ELECTRIC INDUSTRIAL CO., LTD.
98                      GANAN CALVO, Alfonso
99                               WANG, Kemin

[100 rows x 1 columns]

## ADDRESS_1

First address line of a person. Default value: empty. In PATSTAT Online these attributes are not populated.

In [14]:
addr1 = db.query(
    REG107_PARTIES.id,
    REG107_PARTIES.name,
    REG107_PARTIES.address_1
).limit(100)

addr1_df = patstat.df(addr1)
addr1_df

          id                              name address_1
0   22745149                       SHI, Jingbo
1   15726078                  CZANIERA, Jürgen
2   20830107                    SMS Group GmbH
3   20172637                    Tröger, Sascha
4   13002426                Gunzelmann, Rainer
..       ...                               ...       ...
95  14892344                          CHAI, Li
96  13741872               GEHRMANN, Christian
97  16160506                    Kuebler, Jakob
98   7742913                   INOUE, Hiroyuki
99  94101523  Hutchins, Michael Richard, et al

[100 rows x 3 columns]

## ADDRESS_2

Second address line of a person. Default value: empty. In PATSTAT Online these attributes are not populated.

In [15]:
addr2 = db.query(
    REG107_PARTIES.id,
    REG107_PARTIES.name,
    REG107_PARTIES.address_2
).limit(100)

addr2_df = patstat.df(addr2)
addr2_df

          id                         name address_2
0    6735552          ABBOTT LABORATORIES
1   16775894                  WOOD, Barry
2   20830924                   Fitbit LLC
3   18731731               BARGAJE, Kedar
4   15867040              Kao Corporation
..       ...                          ...       ...
95  94922656         BUTKIEWICZ, John, D.
96   4767729                    Regimbeau
97   8754383       Mareschal, Anne, et al
98  99300825  Sturt, Clifford Mark, et al
99   4077985               Peleman, Guido

[100 rows x 3 columns]

## ADDRESS_3

Third address line of a person. Default value: empty. In PATSTAT Online these attributes are not populated.

From `address_3` onwards, there are not many applicants with an *n*-th address, with *n* > 3. Therefore, we filter the addresses that do not consist of an empty string.

In [16]:
addr3 = db.query(
    REG107_PARTIES.id,
    REG107_PARTIES.name,
    REG107_PARTIES.address_3
).filter(
    REG107_PARTIES.address_3 != ''
)

addr3_df = patstat.df(addr3)
addr3_df

Empty DataFrame
Columns: []
Index: []

## ADDRESS_4

Fourth address line of a person. Default value: empty. In PATSTAT Online these attributes are not populated.

In [17]:
addr4 = db.query(
    REG107_PARTIES.id,
    REG107_PARTIES.name,
    REG107_PARTIES.address_4
).filter(
    REG107_PARTIES.address_4 != ''
)

addr4_df = patstat.df(addr4)
addr4_df

Empty DataFrame
Columns: []
Index: []

## ADDRESS_5

Fifth address line of a person. Default value: empty. In PATSTAT Online these attributes are not populated.

In [18]:
addr5 = db.query(
    REG107_PARTIES.id,
    REG107_PARTIES.name,
    REG107_PARTIES.address_5
).filter(
    REG107_PARTIES.address_5 != ''
)

addr5_df = patstat.df(addr5)
addr5_df

Empty DataFrame
Columns: []
Index: []

## COUNTRY

Two-letter country/territory code for patent parties (applicant/inventor/agent), designated states of applicant, or country of licensees. Default value: empty. The domain consists of up to 2 alphabetic characters, according to WIPO ST.3, plus minor additions.

Let's check which are the most frequent countries/territories for patent parties.

In [19]:
country = db.query(
    REG107_PARTIES.country,
    func.count(REG107_PARTIES.id).label('number_of_applications')
).group_by(
    REG107_PARTIES.country
).order_by(
    func.count(REG107_PARTIES.id).desc()
)

country_df = patstat.df(country)
country_df

    country  number_of_applications
0        US                 9277013
1        DE                 8017496
2        JP                 5919344
3        GB                 3817726
4        CN                 3162566
..      ...                     ...
289      Se                       1
290      at                       1
291      SP                       1
292      Us                       1
293      Fr                       1

[294 rows x 2 columns]