# The REG110_TITLE table

Welcome to table **REG110_TITLE** of PATSTAT Register. This table contains the titles of the patent applications in the official languages of the EPO (English, French, and German), as far as available at the time published in the Gazette.

In [1]:
from epo.tipdata.patstat import PatstatClient
from epo.tipdata.patstat.database.models import REG110_TITLE
from sqlalchemy import func
import pandas as pd

# Initialise the PATSTAT client
patstat = PatstatClient(env='PROD')

# Access ORM
db = patstat.orm()

## ID (Primary Key)

Technical identifier for an application, without business meaning. Its values will not change from one PATSTAT edition to the next.

In [2]:
i = db.query(
    REG110_TITLE.id
).limit(1000)

df = patstat.df(i)
df

           id
0    84308495
1    19204592
2    98933140
3     9746175
4    13727032
..        ...
995    307485
996  19215501
997  18878627
998  12725893
999  16731452

[1000 rows x 1 columns]

## CHANGE DATE

It is the date of when the record was saved in the database.

In [3]:
change_date = db.query(
    REG110_TITLE.change_date,
    REG110_TITLE.id
).limit(100)

change_date_df = patstat.df(change_date)
change_date_df

   change_date        id
0   2014-09-13  14759607
1   2019-07-03  17809037
2   2022-02-04  20947139
3   1993-07-29  93103964
4   2007-02-02   5760761
..         ...       ...
95  2025-04-12  24875042
96  2005-12-30   4752017
97  1981-08-22  81301446
98  1998-08-07  96944228
99  2021-12-03  21193065

[100 rows x 2 columns]

## BULLETIN_YEAR

For actions that have been published in the European Patent Bulletin, it is the year of the publication in the European Patent Bulletin. The default value is 0, used for applications that are not published or for which the year is not known. The format is YYYY otherwise.

In [4]:
years = db.query(
    REG110_TITLE.bulletin_year,
    REG110_TITLE.id
).limit(1000)

years_df = patstat.df(years)
years_df

     bulletin_year        id
0             2012  10789695
1             1999  98870111
2             1990  89118288
3             2023  21759049
4             2020  18749928
..             ...       ...
995           2012  10713171
996           1989  89304605
997              0  20959526
998           1998  97201376
999              0   7718152

[1000 rows x 2 columns]

## BULLETIN_NR

This is the issue number of the European Patent Bulletin for actions that have been published in it. This attribute indicates the calendar week the European Patent Bulletin was published. The default value 0 is used when the attribute `bulletin_year` is 0.

In [5]:
bulletin_nr = db.query(
    REG110_TITLE.id,
    REG110_TITLE.bulletin_nr,
    REG110_TITLE.bulletin_year
).limit(100)

bulletin_nr_df = patstat.df(bulletin_nr)
bulletin_nr_df

          id  bulletin_nr  bulletin_year
0   10789695           17           2012
1   98870111           17           1999
2   89118288           15           1990
3   21759049           24           2023
4   18749928           22           2020
..       ...          ...            ...
95  83109736           17           1984
96  96401452            5           1997
97  20895290            0              0
98   5764027           19           2007
99  16902553           13           2019

[100 rows x 3 columns]

## TITLE_LG

The language of the application title. It can be English, French or German.

Let's see what is the most frequent language for titles in PATSTAT Register.

In [6]:
title_lg = db.query(
    REG110_TITLE.title_lg,
    func.count(REG110_TITLE.id).label('number_of_applications')
).group_by(
    REG110_TITLE.title_lg
).order_by(
    func.count(REG110_TITLE.id).desc()
)

title_lg_df = patstat.df(title_lg)
title_lg_df

  title_lg  number_of_applications
0       fr                 7711469
1       en                 7615953
2       de                 5315710

## TITLE

The title of the patent application in an official language of the EPO.

For example, we can retrieve all the titles in French by using the attribute `title_lg`.

In [7]:
title = db.query(
    REG110_TITLE.title
).filter(
    REG110_TITLE.title_lg == 'fr'
).limit(100)

title_df = patstat.df(title)
title_df

                                                title
0   PROCEDE ET SYSTEME DE POSITIONNEMENT D'UNE STA...
1   CONCEPT D'ESSIEU MODULAIRE POUR UN VÉHICULE À ...
2   DISPOSITIF DE DISTILLATION DE DIFFÉRENTS TYPES...
3   PROCÉDÉ DE DÉLÉGATION DE PRIVILÈGES À UNE INST...
4   PROCÉDÉ ET ROBINET DE PROTECTION CONTRE LE COU...
..                                                ...
95  SUBSTRAT DE CIRCUIT, SUBSTRAT POUR CARTE SONDE...
96  ROUE DENTÉE POUR BANDE TRANSPORTEUSE SOUPLE ET...
97                         CONVERTISSEUR DE PUISSANCE
98        ÉMULSION COSMÉTIQUE À MOUSSAGE BLANC RÉDUIT
99                    EMPILEMENT D'OBTURATEURS MINCES

[100 rows x 1 columns]